# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/responses/ChangeSellerResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gateway.models import HeaderValue_pb2 as gateway_dot_models_dot_HeaderValue__pb2
from executor.response import ChangeSellerViewResponse_pb2 as executor_dot_response_dot_ChangeSellerViewResponse__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway/responses/ChangeSellerResponse.proto',
  package='fkhp.gateway.layer.client.response',
  syntax='proto3',
  serialized_options=_b('\n\"fkhp.gateway.layer.client.responseP\001'),
  serialized_pb=_b('\n,gateway/responses/ChangeSellerResponse.proto\x12\"fkhp.gateway.layer.client.response\x1a gateway/models/HeaderValue.proto\x1a\x30\x65xecutor/response/ChangeSellerViewResponse.proto\"\x9f\x02\n\x14\x43hangeSellerResponse\x12M\n\x08response\x18\x01 \x01(\x0b\x32;.fkhp.data.layer.executor.response.ChangeSellerViewResponse\x12X\n\x08metadata\x18\x02 \x03(\x0b\x32\x46.fkhp.gateway.layer.client.response.ChangeSellerResponse.MetadataEntry\x1a^\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12<\n\x05value\x18\x02 \x01(\x0b\x32-.fkhp.gateway.layer.client.models.HeaderValue:\x02\x38\x01\x42&\n\"fkhp.gateway.layer.client.responseP\x01\x62\x06proto3')
  ,
  dependencies=[gateway_dot_models_dot_HeaderValue__pb2.DESCRIPTOR,executor_dot_response_dot_ChangeSellerViewResponse__pb2.DESCRIPTOR,])




_CHANGESELLERRESPONSE_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='fkhp.gateway.layer.client.response.ChangeSellerResponse.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='fkhp.gateway.layer.client.response.ChangeSellerResponse.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='fkhp.gateway.layer.client.response.ChangeSellerResponse.MetadataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=456,
)

_CHANGESELLERRESPONSE = _descriptor.Descriptor(
  name='ChangeSellerResponse',
  full_name='fkhp.gateway.layer.client.response.ChangeSellerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='fkhp.gateway.layer.client.response.ChangeSellerResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='fkhp.gateway.layer.client.response.ChangeSellerResponse.metadata', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CHANGESELLERRESPONSE_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=456,
)

_CHANGESELLERRESPONSE_METADATAENTRY.fields_by_name['value'].message_type = gateway_dot_models_dot_HeaderValue__pb2._HEADERVALUE
_CHANGESELLERRESPONSE_METADATAENTRY.containing_type = _CHANGESELLERRESPONSE
_CHANGESELLERRESPONSE.fields_by_name['response'].message_type = executor_dot_response_dot_ChangeSellerViewResponse__pb2._CHANGESELLERVIEWRESPONSE
_CHANGESELLERRESPONSE.fields_by_name['metadata'].message_type = _CHANGESELLERRESPONSE_METADATAENTRY
DESCRIPTOR.message_types_by_name['ChangeSellerResponse'] = _CHANGESELLERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChangeSellerResponse = _reflection.GeneratedProtocolMessageType('ChangeSellerResponse', (_message.Message,), dict(

  MetadataEntry = _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), dict(
    DESCRIPTOR = _CHANGESELLERRESPONSE_METADATAENTRY,
    __module__ = 'gateway.responses.ChangeSellerResponse_pb2'
    # @@protoc_insertion_point(class_scope:fkhp.gateway.layer.client.response.ChangeSellerResponse.MetadataEntry)
    ))
  ,
  DESCRIPTOR = _CHANGESELLERRESPONSE,
  __module__ = 'gateway.responses.ChangeSellerResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.gateway.layer.client.response.ChangeSellerResponse)
  ))
_sym_db.RegisterMessage(ChangeSellerResponse)
_sym_db.RegisterMessage(ChangeSellerResponse.MetadataEntry)


DESCRIPTOR._options = None
_CHANGESELLERRESPONSE_METADATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
