# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/models/genericInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import iconInfo_pb2 as executor_dot_models_dot_iconInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/models/genericInfo.proto',
  package='fkhp.data.layer.executor.models',
  syntax='proto3',
  serialized_options=_b('\n\037fkhp.data.layer.executor.modelsP\001'),
  serialized_pb=_b('\n!executor/models/genericInfo.proto\x12\x1f\x66khp.data.layer.executor.models\x1a\x1e\x65xecutor/models/iconInfo.proto\"\x80\x01\n\x0bGenericInfo\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12;\n\x08iconInfo\x18\x03 \x01(\x0b\x32).fkhp.data.layer.executor.models.IconInfo\x12\x10\n\x08sequence\x18\x04 \x01(\x05\x42#\n\x1f\x66khp.data.layer.executor.modelsP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_iconInfo__pb2.DESCRIPTOR,])




_GENERICINFO = _descriptor.Descriptor(
  name='GenericInfo',
  full_name='fkhp.data.layer.executor.models.GenericInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='fkhp.data.layer.executor.models.GenericInfo.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='fkhp.data.layer.executor.models.GenericInfo.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iconInfo', full_name='fkhp.data.layer.executor.models.GenericInfo.iconInfo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='fkhp.data.layer.executor.models.GenericInfo.sequence', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=231,
)

_GENERICINFO.fields_by_name['iconInfo'].message_type = executor_dot_models_dot_iconInfo__pb2._ICONINFO
DESCRIPTOR.message_types_by_name['GenericInfo'] = _GENERICINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericInfo = _reflection.GeneratedProtocolMessageType('GenericInfo', (_message.Message,), dict(
  DESCRIPTOR = _GENERICINFO,
  __module__ = 'executor.models.genericInfo_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.models.GenericInfo)
  ))
_sym_db.RegisterMessage(GenericInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
