# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/models/medicineInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import saltInfo_pb2 as executor_dot_models_dot_saltInfo__pb2
from executor.models import genericInfo_pb2 as executor_dot_models_dot_genericInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/models/medicineInfo.proto',
  package='fkhp.data.layer.executor.models',
  syntax='proto3',
  serialized_options=_b('\n\037fkhp.data.layer.executor.modelsP\001'),
  serialized_pb=_b('\n\"executor/models/medicineInfo.proto\x12\x1f\x66khp.data.layer.executor.models\x1a\x1e\x65xecutor/models/saltInfo.proto\x1a!executor/models/genericInfo.proto\"\x8a\x01\n\x0cMedicineInfo\x12\x37\n\x04salt\x18\x01 \x01(\x0b\x32).fkhp.data.layer.executor.models.SaltInfo\x12\x41\n\x0bgenericInfo\x18\x02 \x03(\x0b\x32,.fkhp.data.layer.executor.models.GenericInfoB#\n\x1f\x66khp.data.layer.executor.modelsP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_saltInfo__pb2.DESCRIPTOR,executor_dot_models_dot_genericInfo__pb2.DESCRIPTOR,])




_MEDICINEINFO = _descriptor.Descriptor(
  name='MedicineInfo',
  full_name='fkhp.data.layer.executor.models.MedicineInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='salt', full_name='fkhp.data.layer.executor.models.MedicineInfo.salt', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genericInfo', full_name='fkhp.data.layer.executor.models.MedicineInfo.genericInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=277,
)

_MEDICINEINFO.fields_by_name['salt'].message_type = executor_dot_models_dot_saltInfo__pb2._SALTINFO
_MEDICINEINFO.fields_by_name['genericInfo'].message_type = executor_dot_models_dot_genericInfo__pb2._GENERICINFO
DESCRIPTOR.message_types_by_name['MedicineInfo'] = _MEDICINEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MedicineInfo = _reflection.GeneratedProtocolMessageType('MedicineInfo', (_message.Message,), dict(
  DESCRIPTOR = _MEDICINEINFO,
  __module__ = 'executor.models.medicineInfo_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.models.MedicineInfo)
  ))
_sym_db.RegisterMessage(MedicineInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
