# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/models/offerInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/models/offerInfo.proto',
  package='fkhp.data.layer.executor.models',
  syntax='proto3',
  serialized_options=_b('\n\037fkhp.data.layer.executor.modelsP\001'),
  serialized_pb=_b('\n\x1f\x65xecutor/models/offerInfo.proto\x12\x1f\x66khp.data.layer.executor.models\"\xa6\x01\n\tOfferInfo\x12\x0f\n\x07offerId\x18\x01 \x01(\t\x12\x11\n\tofferName\x18\x02 \x01(\t\x12\x18\n\x10offerDescription\x18\x03 \x01(\t\x12\x12\n\nofferImage\x18\x04 \x01(\t\x12\x1d\n\x15offerShortDescription\x18\x05 \x01(\t\x12\x12\n\ncouponCode\x18\x06 \x01(\t\x12\x14\n\x0cvalidityDate\x18\x07 \x01(\tB#\n\x1f\x66khp.data.layer.executor.modelsP\x01\x62\x06proto3')
)




_OFFERINFO = _descriptor.Descriptor(
  name='OfferInfo',
  full_name='fkhp.data.layer.executor.models.OfferInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offerId', full_name='fkhp.data.layer.executor.models.OfferInfo.offerId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offerName', full_name='fkhp.data.layer.executor.models.OfferInfo.offerName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offerDescription', full_name='fkhp.data.layer.executor.models.OfferInfo.offerDescription', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offerImage', full_name='fkhp.data.layer.executor.models.OfferInfo.offerImage', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offerShortDescription', full_name='fkhp.data.layer.executor.models.OfferInfo.offerShortDescription', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='couponCode', full_name='fkhp.data.layer.executor.models.OfferInfo.couponCode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validityDate', full_name='fkhp.data.layer.executor.models.OfferInfo.validityDate', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=235,
)

DESCRIPTOR.message_types_by_name['OfferInfo'] = _OFFERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OfferInfo = _reflection.GeneratedProtocolMessageType('OfferInfo', (_message.Message,), dict(
  DESCRIPTOR = _OFFERINFO,
  __module__ = 'executor.models.offerInfo_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.models.OfferInfo)
  ))
_sym_db.RegisterMessage(OfferInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
