# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/models/paymentDetail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import paymentType_pb2 as executor_dot_models_dot_paymentType__pb2
from executor.models import paymentMode_pb2 as executor_dot_models_dot_paymentMode__pb2
from executor.models import offerInfo_pb2 as executor_dot_models_dot_offerInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/models/paymentDetail.proto',
  package='fkhp.data.layer.executor.models',
  syntax='proto3',
  serialized_options=_b('\n\037fkhp.data.layer.executor.modelsP\001'),
  serialized_pb=_b('\n#executor/models/paymentDetail.proto\x12\x1f\x66khp.data.layer.executor.models\x1a!executor/models/paymentType.proto\x1a!executor/models/paymentMode.proto\x1a\x1f\x65xecutor/models/offerInfo.proto\"\xa8\x03\n\rPaymentDetail\x12\x41\n\x0bpaymentType\x18\x01 \x01(\x0e\x32,.fkhp.data.layer.executor.models.PaymentType\x12\x41\n\x0bpaymentMode\x18\x02 \x01(\x0e\x32,.fkhp.data.layer.executor.models.PaymentMode\x12\x45\n\rpayemntStatus\x18\x03 \x01(\x0e\x32..fkhp.data.layer.executor.models.PaymentStatus\x12\x17\n\x0fpaymentStatusId\x18\x04 \x01(\t\x12\x11\n\tpaymentId\x18\x05 \x01(\t\x12\x15\n\rtransactionId\x18\x06 \x01(\t\x12\x15\n\rdateOfPayment\x18\x07 \x01(\t\x12\x15\n\rpaymentAmount\x18\x08 \x01(\t\x12\x17\n\x0fpaymentDiscount\x18\t \x01(\t\x12@\n\x0cpaymentOffer\x18\n \x01(\x0b\x32*.fkhp.data.layer.executor.models.OfferInfo*%\n\rPaymentStatus\x12\x08\n\x04PAID\x10\x00\x12\n\n\x06UNPAID\x10\x01\x42#\n\x1f\x66khp.data.layer.executor.modelsP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_paymentType__pb2.DESCRIPTOR,executor_dot_models_dot_paymentMode__pb2.DESCRIPTOR,executor_dot_models_dot_offerInfo__pb2.DESCRIPTOR,])

_PAYMENTSTATUS = _descriptor.EnumDescriptor(
  name='PaymentStatus',
  full_name='fkhp.data.layer.executor.models.PaymentStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PAID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNPAID', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=602,
  serialized_end=639,
)
_sym_db.RegisterEnumDescriptor(_PAYMENTSTATUS)

PaymentStatus = enum_type_wrapper.EnumTypeWrapper(_PAYMENTSTATUS)
PAID = 0
UNPAID = 1



_PAYMENTDETAIL = _descriptor.Descriptor(
  name='PaymentDetail',
  full_name='fkhp.data.layer.executor.models.PaymentDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paymentType', full_name='fkhp.data.layer.executor.models.PaymentDetail.paymentType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paymentMode', full_name='fkhp.data.layer.executor.models.PaymentDetail.paymentMode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payemntStatus', full_name='fkhp.data.layer.executor.models.PaymentDetail.payemntStatus', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paymentStatusId', full_name='fkhp.data.layer.executor.models.PaymentDetail.paymentStatusId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paymentId', full_name='fkhp.data.layer.executor.models.PaymentDetail.paymentId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactionId', full_name='fkhp.data.layer.executor.models.PaymentDetail.transactionId', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dateOfPayment', full_name='fkhp.data.layer.executor.models.PaymentDetail.dateOfPayment', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paymentAmount', full_name='fkhp.data.layer.executor.models.PaymentDetail.paymentAmount', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paymentDiscount', full_name='fkhp.data.layer.executor.models.PaymentDetail.paymentDiscount', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paymentOffer', full_name='fkhp.data.layer.executor.models.PaymentDetail.paymentOffer', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=600,
)

_PAYMENTDETAIL.fields_by_name['paymentType'].enum_type = executor_dot_models_dot_paymentType__pb2._PAYMENTTYPE
_PAYMENTDETAIL.fields_by_name['paymentMode'].enum_type = executor_dot_models_dot_paymentMode__pb2._PAYMENTMODE
_PAYMENTDETAIL.fields_by_name['payemntStatus'].enum_type = _PAYMENTSTATUS
_PAYMENTDETAIL.fields_by_name['paymentOffer'].message_type = executor_dot_models_dot_offerInfo__pb2._OFFERINFO
DESCRIPTOR.message_types_by_name['PaymentDetail'] = _PAYMENTDETAIL
DESCRIPTOR.enum_types_by_name['PaymentStatus'] = _PAYMENTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PaymentDetail = _reflection.GeneratedProtocolMessageType('PaymentDetail', (_message.Message,), dict(
  DESCRIPTOR = _PAYMENTDETAIL,
  __module__ = 'executor.models.paymentDetail_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.models.PaymentDetail)
  ))
_sym_db.RegisterMessage(PaymentDetail)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
