# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/models/ratingSummary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/models/ratingSummary.proto',
  package='fkhp.data.layer.executor.models',
  syntax='proto3',
  serialized_options=_b('\n\037fkhp.data.layer.executor.modelsP\001'),
  serialized_pb=_b('\n#executor/models/ratingSummary.proto\x12\x1f\x66khp.data.layer.executor.models\"\xcc\x01\n\rRatingSummary\x12\x15\n\roverallRating\x18\x01 \x01(\x01\x12\x19\n\x11maxRatingPossible\x18\x02 \x01(\x05\x12\x1c\n\x14totalNumberOfRatings\x18\x03 \x01(\x05\x12O\n\x12ratingDistribution\x18\x04 \x01(\x0b\x32\x33.fkhp.data.layer.executor.models.RatingDistribution\x12\x1a\n\x12isProductPurchased\x18\x05 \x01(\x08\"i\n\x12RatingDistribution\x12\x0f\n\x07rating1\x18\x01 \x01(\x01\x12\x0f\n\x07rating2\x18\x02 \x01(\x01\x12\x0f\n\x07rating3\x18\x03 \x01(\x01\x12\x0f\n\x07rating4\x18\x04 \x01(\x01\x12\x0f\n\x07rating5\x18\x05 \x01(\x01\x42#\n\x1f\x66khp.data.layer.executor.modelsP\x01\x62\x06proto3')
)




_RATINGSUMMARY = _descriptor.Descriptor(
  name='RatingSummary',
  full_name='fkhp.data.layer.executor.models.RatingSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='overallRating', full_name='fkhp.data.layer.executor.models.RatingSummary.overallRating', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxRatingPossible', full_name='fkhp.data.layer.executor.models.RatingSummary.maxRatingPossible', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalNumberOfRatings', full_name='fkhp.data.layer.executor.models.RatingSummary.totalNumberOfRatings', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ratingDistribution', full_name='fkhp.data.layer.executor.models.RatingSummary.ratingDistribution', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isProductPurchased', full_name='fkhp.data.layer.executor.models.RatingSummary.isProductPurchased', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=277,
)


_RATINGDISTRIBUTION = _descriptor.Descriptor(
  name='RatingDistribution',
  full_name='fkhp.data.layer.executor.models.RatingDistribution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rating1', full_name='fkhp.data.layer.executor.models.RatingDistribution.rating1', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating2', full_name='fkhp.data.layer.executor.models.RatingDistribution.rating2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating3', full_name='fkhp.data.layer.executor.models.RatingDistribution.rating3', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating4', full_name='fkhp.data.layer.executor.models.RatingDistribution.rating4', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating5', full_name='fkhp.data.layer.executor.models.RatingDistribution.rating5', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=384,
)

_RATINGSUMMARY.fields_by_name['ratingDistribution'].message_type = _RATINGDISTRIBUTION
DESCRIPTOR.message_types_by_name['RatingSummary'] = _RATINGSUMMARY
DESCRIPTOR.message_types_by_name['RatingDistribution'] = _RATINGDISTRIBUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RatingSummary = _reflection.GeneratedProtocolMessageType('RatingSummary', (_message.Message,), dict(
  DESCRIPTOR = _RATINGSUMMARY,
  __module__ = 'executor.models.ratingSummary_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.models.RatingSummary)
  ))
_sym_db.RegisterMessage(RatingSummary)

RatingDistribution = _reflection.GeneratedProtocolMessageType('RatingDistribution', (_message.Message,), dict(
  DESCRIPTOR = _RATINGDISTRIBUTION,
  __module__ = 'executor.models.ratingSummary_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.models.RatingDistribution)
  ))
_sym_db.RegisterMessage(RatingDistribution)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
