# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/response/AddComponentResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/response/AddComponentResponse.proto',
  package='fkhp.page.layer.response',
  syntax='proto3',
  serialized_options=_b('\n\030fkhp.page.layer.responseP\001'),
  serialized_pb=_b('\n(page/response/AddComponentResponse.proto\x12\x18\x66khp.page.layer.response\"@\n\x14\x41\x64\x64\x43omponentResponse\x12\x15\n\rsectionCompId\x18\x01 \x01(\t\x12\x11\n\tcompOrder\x18\x02 \x01(\x05\x42\x1c\n\x18\x66khp.page.layer.responseP\x01\x62\x06proto3')
)




_ADDCOMPONENTRESPONSE = _descriptor.Descriptor(
  name='AddComponentResponse',
  full_name='fkhp.page.layer.response.AddComponentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sectionCompId', full_name='fkhp.page.layer.response.AddComponentResponse.sectionCompId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compOrder', full_name='fkhp.page.layer.response.AddComponentResponse.compOrder', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['AddComponentResponse'] = _ADDCOMPONENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddComponentResponse = _reflection.GeneratedProtocolMessageType('AddComponentResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDCOMPONENTRESPONSE,
  __module__ = 'page.response.AddComponentResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.page.layer.response.AddComponentResponse)
  ))
_sym_db.RegisterMessage(AddComponentResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
