# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/response/PageResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/response/PageResponse.proto',
  package='fkhp.page.layer.response',
  syntax='proto3',
  serialized_options=_b('\n\030fkhp.page.layer.responseP\001'),
  serialized_pb=_b('\n page/response/PageResponse.proto\x12\x18\x66khp.page.layer.response\"\x1e\n\x0cPageResponse\x12\x0e\n\x06pageId\x18\x01 \x01(\tB\x1c\n\x18\x66khp.page.layer.responseP\x01\x62\x06proto3')
)




_PAGERESPONSE = _descriptor.Descriptor(
  name='PageResponse',
  full_name='fkhp.page.layer.response.PageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pageId', full_name='fkhp.page.layer.response.PageResponse.pageId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['PageResponse'] = _PAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PageResponse = _reflection.GeneratedProtocolMessageType('PageResponse', (_message.Message,), dict(
  DESCRIPTOR = _PAGERESPONSE,
  __module__ = 'page.response.PageResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.page.layer.response.PageResponse)
  ))
_sym_db.RegisterMessage(PageResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
