# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from gateway.requests import AddAddressRequest_pb2 as gateway_dot_requests_dot_AddAddressRequest__pb2
from gateway.requests import AddressBookRequest_pb2 as gateway_dot_requests_dot_AddressBookRequest__pb2
from gateway.requests import EditAddressRequest_pb2 as gateway_dot_requests_dot_EditAddressRequest__pb2
from gateway.requests import NearestAreaRequest_pb2 as gateway_dot_requests_dot_NearestAreaRequest__pb2
from gateway.requests import RemoveAddressRequest_pb2 as gateway_dot_requests_dot_RemoveAddressRequest__pb2
from gateway.responses import AddAddressResponse_pb2 as gateway_dot_responses_dot_AddAddressResponse__pb2
from gateway.responses import AddressBookResponse_pb2 as gateway_dot_responses_dot_AddressBookResponse__pb2
from gateway.responses import EditAddressResponse_pb2 as gateway_dot_responses_dot_EditAddressResponse__pb2
from gateway.responses import NearestAreaResponse_pb2 as gateway_dot_responses_dot_NearestAreaResponse__pb2
from gateway.responses import RemoveAddressResponse_pb2 as gateway_dot_responses_dot_RemoveAddressResponse__pb2


class AddressServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.addAddress = channel.unary_unary(
        '/fkhp.gateway.layer.client.AddressService/addAddress',
        request_serializer=gateway_dot_requests_dot_AddAddressRequest__pb2.AddAddressRequest.SerializeToString,
        response_deserializer=gateway_dot_responses_dot_AddAddressResponse__pb2.AddAddressResponse.FromString,
        )
    self.editAddress = channel.unary_unary(
        '/fkhp.gateway.layer.client.AddressService/editAddress',
        request_serializer=gateway_dot_requests_dot_EditAddressRequest__pb2.EditAddressRequest.SerializeToString,
        response_deserializer=gateway_dot_responses_dot_EditAddressResponse__pb2.EditAddressResponse.FromString,
        )
    self.removeAddress = channel.unary_unary(
        '/fkhp.gateway.layer.client.AddressService/removeAddress',
        request_serializer=gateway_dot_requests_dot_RemoveAddressRequest__pb2.RemoveAddressRequest.SerializeToString,
        response_deserializer=gateway_dot_responses_dot_RemoveAddressResponse__pb2.RemoveAddressResponse.FromString,
        )
    self.NearestArea = channel.unary_unary(
        '/fkhp.gateway.layer.client.AddressService/NearestArea',
        request_serializer=gateway_dot_requests_dot_NearestAreaRequest__pb2.NearestAreaRequest.SerializeToString,
        response_deserializer=gateway_dot_responses_dot_NearestAreaResponse__pb2.NearestAreaResponse.FromString,
        )
    self.getAddressBook = channel.unary_unary(
        '/fkhp.gateway.layer.client.AddressService/getAddressBook',
        request_serializer=gateway_dot_requests_dot_AddressBookRequest__pb2.AddressBookRequest.SerializeToString,
        response_deserializer=gateway_dot_responses_dot_AddressBookResponse__pb2.AddressBookResponse.FromString,
        )


class AddressServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def addAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def editAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def removeAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NearestArea(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAddressBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AddressServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'addAddress': grpc.unary_unary_rpc_method_handler(
          servicer.addAddress,
          request_deserializer=gateway_dot_requests_dot_AddAddressRequest__pb2.AddAddressRequest.FromString,
          response_serializer=gateway_dot_responses_dot_AddAddressResponse__pb2.AddAddressResponse.SerializeToString,
      ),
      'editAddress': grpc.unary_unary_rpc_method_handler(
          servicer.editAddress,
          request_deserializer=gateway_dot_requests_dot_EditAddressRequest__pb2.EditAddressRequest.FromString,
          response_serializer=gateway_dot_responses_dot_EditAddressResponse__pb2.EditAddressResponse.SerializeToString,
      ),
      'removeAddress': grpc.unary_unary_rpc_method_handler(
          servicer.removeAddress,
          request_deserializer=gateway_dot_requests_dot_RemoveAddressRequest__pb2.RemoveAddressRequest.FromString,
          response_serializer=gateway_dot_responses_dot_RemoveAddressResponse__pb2.RemoveAddressResponse.SerializeToString,
      ),
      'NearestArea': grpc.unary_unary_rpc_method_handler(
          servicer.NearestArea,
          request_deserializer=gateway_dot_requests_dot_NearestAreaRequest__pb2.NearestAreaRequest.FromString,
          response_serializer=gateway_dot_responses_dot_NearestAreaResponse__pb2.NearestAreaResponse.SerializeToString,
      ),
      'getAddressBook': grpc.unary_unary_rpc_method_handler(
          servicer.getAddressBook,
          request_deserializer=gateway_dot_requests_dot_AddressBookRequest__pb2.AddressBookRequest.FromString,
          response_serializer=gateway_dot_responses_dot_AddressBookResponse__pb2.AddressBookResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fkhp.gateway.layer.client.AddressService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
