# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/clients/FetchClient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gateway.requests import FetchPageRequest_pb2 as gateway_dot_requests_dot_FetchPageRequest__pb2
from gateway.responses import FetchResponse_pb2 as gateway_dot_responses_dot_FetchResponse__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway/clients/FetchClient.proto',
  package='fkhp.gateway.layer.client',
  syntax='proto3',
  serialized_options=_b('\n\031fkhp.gateway.layer.clientP\001'),
  serialized_pb=_b('\n!gateway/clients/FetchClient.proto\x12\x19\x66khp.gateway.layer.client\x1a\'gateway/requests/FetchPageRequest.proto\x1a%gateway/responses/FetchResponse.proto\x1a\x1cgoogle/api/annotations.proto2\x9a\x01\n\x0b\x46\x65tchClient\x12\x8a\x01\n\x05\x66\x65tch\x12\x34.fkhp.gateway.layer.client.requests.FetchPageRequest\x1a\x31.fkhp.gateway.layer.client.response.FetchResponse\"\x18\x82\xd3\xe4\x93\x02\x12\"\r/v1/fetchpage:\x01*B\x1d\n\x19\x66khp.gateway.layer.clientP\x01\x62\x06proto3')
  ,
  dependencies=[gateway_dot_requests_dot_FetchPageRequest__pb2.DESCRIPTOR,gateway_dot_responses_dot_FetchResponse__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_FETCHCLIENT = _descriptor.ServiceDescriptor(
  name='FetchClient',
  full_name='fkhp.gateway.layer.client.FetchClient',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=175,
  serialized_end=329,
  methods=[
  _descriptor.MethodDescriptor(
    name='fetch',
    full_name='fkhp.gateway.layer.client.FetchClient.fetch',
    index=0,
    containing_service=None,
    input_type=gateway_dot_requests_dot_FetchPageRequest__pb2._FETCHPAGEREQUEST,
    output_type=gateway_dot_responses_dot_FetchResponse__pb2._FETCHRESPONSE,
    serialized_options=_b('\202\323\344\223\002\022\"\r/v1/fetchpage:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_FETCHCLIENT)

DESCRIPTOR.services_by_name['FetchClient'] = _FETCHCLIENT

# @@protoc_insertion_point(module_scope)
