# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/clients/PostService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gateway.requests import PostActionsRequest_pb2 as gateway_dot_requests_dot_PostActionsRequest__pb2
from gateway.responses import PostActionsResponse_pb2 as gateway_dot_responses_dot_PostActionsResponse__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway/clients/PostService.proto',
  package='fkhp.gateway.layer.client',
  syntax='proto3',
  serialized_options=_b('\n\031fkhp.gateway.layer.clientP\001'),
  serialized_pb=_b('\n!gateway/clients/PostService.proto\x12\x19\x66khp.gateway.layer.client\x1a)gateway/requests/PostActionsRequest.proto\x1a+gateway/responses/PostActionsResponse.proto2\x91\x01\n\x0bPostService\x12\x81\x01\n\x0c\x64oPostAction\x12\x36.fkhp.gateway.layer.client.requests.PostActionsRequest\x1a\x37.fkhp.gateway.layer.client.response.PostActionsResponse\"\x00\x42\x1d\n\x19\x66khp.gateway.layer.clientP\x01\x62\x06proto3')
  ,
  dependencies=[gateway_dot_requests_dot_PostActionsRequest__pb2.DESCRIPTOR,gateway_dot_responses_dot_PostActionsResponse__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_POSTSERVICE = _descriptor.ServiceDescriptor(
  name='PostService',
  full_name='fkhp.gateway.layer.client.PostService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=153,
  serialized_end=298,
  methods=[
  _descriptor.MethodDescriptor(
    name='doPostAction',
    full_name='fkhp.gateway.layer.client.PostService.doPostAction',
    index=0,
    containing_service=None,
    input_type=gateway_dot_requests_dot_PostActionsRequest__pb2._POSTACTIONSREQUEST,
    output_type=gateway_dot_responses_dot_PostActionsResponse__pb2._POSTACTIONSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSTSERVICE)

DESCRIPTOR.services_by_name['PostService'] = _POSTSERVICE

# @@protoc_insertion_point(module_scope)
