# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from gateway.requests import TrackOrderRequest_pb2 as gateway_dot_requests_dot_TrackOrderRequest__pb2
from gateway.requests import TrackReturnRequest_pb2 as gateway_dot_requests_dot_TrackReturnRequest__pb2
from gateway.responses import TrackOrderResponse_pb2 as gateway_dot_responses_dot_TrackOrderResponse__pb2
from gateway.responses import TrackReturnResponse_pb2 as gateway_dot_responses_dot_TrackReturnResponse__pb2


class TrackServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getTrackOrderDetails = channel.unary_unary(
        '/fkhp.gateway.layer.client.TrackService/getTrackOrderDetails',
        request_serializer=gateway_dot_requests_dot_TrackOrderRequest__pb2.TrackOrderRequest.SerializeToString,
        response_deserializer=gateway_dot_responses_dot_TrackOrderResponse__pb2.TrackOrderResponse.FromString,
        )
    self.getTrackReturnDetails = channel.unary_unary(
        '/fkhp.gateway.layer.client.TrackService/getTrackReturnDetails',
        request_serializer=gateway_dot_requests_dot_TrackReturnRequest__pb2.TrackReturnRequest.SerializeToString,
        response_deserializer=gateway_dot_responses_dot_TrackReturnResponse__pb2.TrackReturnResponse.FromString,
        )


class TrackServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getTrackOrderDetails(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getTrackReturnDetails(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TrackServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getTrackOrderDetails': grpc.unary_unary_rpc_method_handler(
          servicer.getTrackOrderDetails,
          request_deserializer=gateway_dot_requests_dot_TrackOrderRequest__pb2.TrackOrderRequest.FromString,
          response_serializer=gateway_dot_responses_dot_TrackOrderResponse__pb2.TrackOrderResponse.SerializeToString,
      ),
      'getTrackReturnDetails': grpc.unary_unary_rpc_method_handler(
          servicer.getTrackReturnDetails,
          request_deserializer=gateway_dot_requests_dot_TrackReturnRequest__pb2.TrackReturnRequest.FromString,
          response_serializer=gateway_dot_responses_dot_TrackReturnResponse__pb2.TrackReturnResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fkhp.gateway.layer.client.TrackService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
