# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from gateway.requests import UltraLoginRequest_pb2 as gateway_dot_requests_dot_UltraLoginRequest__pb2
from gateway.responses import UltraLoginResponse_pb2 as gateway_dot_responses_dot_UltraLoginResponse__pb2


class UltraServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ultraLogin = channel.unary_unary(
        '/fkhp.gateway.layer.client.UltraService/ultraLogin',
        request_serializer=gateway_dot_requests_dot_UltraLoginRequest__pb2.UltraLoginRequest.SerializeToString,
        response_deserializer=gateway_dot_responses_dot_UltraLoginResponse__pb2.UltraLoginResponse.FromString,
        )


class UltraServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ultraLogin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UltraServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ultraLogin': grpc.unary_unary_rpc_method_handler(
          servicer.ultraLogin,
          request_deserializer=gateway_dot_requests_dot_UltraLoginRequest__pb2.UltraLoginRequest.FromString,
          response_serializer=gateway_dot_responses_dot_UltraLoginResponse__pb2.UltraLoginResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fkhp.gateway.layer.client.UltraService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
