# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/response/pmp/FetchUiComponentMetaDataResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from page.models.component.pmp import UIComponentMetaData_pb2 as page_dot_models_dot_component_dot_pmp_dot_UIComponentMetaData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/response/pmp/FetchUiComponentMetaDataResponse.proto',
  package='fkhp.page.layer.response.pmp',
  syntax='proto3',
  serialized_options=_b('\n\034fkhp.page.layer.response.pmpP\001'),
  serialized_pb=_b('\n8page/response/pmp/FetchUiComponentMetaDataResponse.proto\x12\x1c\x66khp.page.layer.response.pmp\x1a\x33page/models/component/pmp/UIComponentMetaData.proto\"\xa1\x01\n FetchUiComponentMetaDataResponse\x12\x15\n\ruiComponentId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12V\n\x13uiComponentMetaData\x18\x03 \x01(\x0b\x32\x39.fkhp.page.layer.models.component.pmp.UIComponentMetaDataB \n\x1c\x66khp.page.layer.response.pmpP\x01\x62\x06proto3')
  ,
  dependencies=[page_dot_models_dot_component_dot_pmp_dot_UIComponentMetaData__pb2.DESCRIPTOR,])




_FETCHUICOMPONENTMETADATARESPONSE = _descriptor.Descriptor(
  name='FetchUiComponentMetaDataResponse',
  full_name='fkhp.page.layer.response.pmp.FetchUiComponentMetaDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uiComponentId', full_name='fkhp.page.layer.response.pmp.FetchUiComponentMetaDataResponse.uiComponentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='fkhp.page.layer.response.pmp.FetchUiComponentMetaDataResponse.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uiComponentMetaData', full_name='fkhp.page.layer.response.pmp.FetchUiComponentMetaDataResponse.uiComponentMetaData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=305,
)

_FETCHUICOMPONENTMETADATARESPONSE.fields_by_name['uiComponentMetaData'].message_type = page_dot_models_dot_component_dot_pmp_dot_UIComponentMetaData__pb2._UICOMPONENTMETADATA
DESCRIPTOR.message_types_by_name['FetchUiComponentMetaDataResponse'] = _FETCHUICOMPONENTMETADATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FetchUiComponentMetaDataResponse = _reflection.GeneratedProtocolMessageType('FetchUiComponentMetaDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _FETCHUICOMPONENTMETADATARESPONSE,
  __module__ = 'page.response.pmp.FetchUiComponentMetaDataResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.page.layer.response.pmp.FetchUiComponentMetaDataResponse)
  ))
_sym_db.RegisterMessage(FetchUiComponentMetaDataResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
