# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/response/pmp/FetchAllPageTemplateInProductionResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from page.response import PageTemplate_pb2 as page_dot_response_dot_PageTemplate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/response/pmp/FetchAllPageTemplateInProductionResponse.proto',
  package='fkhp.page.layer.response.pmp',
  syntax='proto3',
  serialized_options=_b('\n\034fkhp.page.layer.response.pmpP\001'),
  serialized_pb=_b('\n@page/response/pmp/FetchAllPageTemplateInProductionResponse.proto\x12\x1c\x66khp.page.layer.response.pmp\x1a page/response/PageTemplate.proto\"x\n(FetchAllPageTemplateInProductionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12<\n\x0cpageTemplate\x18\x02 \x03(\x0b\x32&.fkhp.page.layer.response.PageTemplateB \n\x1c\x66khp.page.layer.response.pmpP\x01\x62\x06proto3')
  ,
  dependencies=[page_dot_response_dot_PageTemplate__pb2.DESCRIPTOR,])




_FETCHALLPAGETEMPLATEINPRODUCTIONRESPONSE = _descriptor.Descriptor(
  name='FetchAllPageTemplateInProductionResponse',
  full_name='fkhp.page.layer.response.pmp.FetchAllPageTemplateInProductionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='fkhp.page.layer.response.pmp.FetchAllPageTemplateInProductionResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageTemplate', full_name='fkhp.page.layer.response.pmp.FetchAllPageTemplateInProductionResponse.pageTemplate', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=252,
)

_FETCHALLPAGETEMPLATEINPRODUCTIONRESPONSE.fields_by_name['pageTemplate'].message_type = page_dot_response_dot_PageTemplate__pb2._PAGETEMPLATE
DESCRIPTOR.message_types_by_name['FetchAllPageTemplateInProductionResponse'] = _FETCHALLPAGETEMPLATEINPRODUCTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FetchAllPageTemplateInProductionResponse = _reflection.GeneratedProtocolMessageType('FetchAllPageTemplateInProductionResponse', (_message.Message,), dict(
  DESCRIPTOR = _FETCHALLPAGETEMPLATEINPRODUCTIONRESPONSE,
  __module__ = 'page.response.pmp.FetchAllPageTemplateInProductionResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.page.layer.response.pmp.FetchAllPageTemplateInProductionResponse)
  ))
_sym_db.RegisterMessage(FetchAllPageTemplateInProductionResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
