# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/response/pmp/ReorderSectionResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/response/pmp/ReorderSectionResponse.proto',
  package='fkhp.page.layer.response.pmp',
  syntax='proto3',
  serialized_options=_b('\n\034fkhp.page.layer.response.pmpP\001'),
  serialized_pb=_b('\n.page/response/pmp/ReorderSectionResponse.proto\x12\x1c\x66khp.page.layer.response.pmp\"M\n\x16ReorderSectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tsectionId\x18\x02 \x01(\t\x12\x10\n\x08newOrder\x18\x03 \x01(\x05\x42 \n\x1c\x66khp.page.layer.response.pmpP\x01\x62\x06proto3')
)




_REORDERSECTIONRESPONSE = _descriptor.Descriptor(
  name='ReorderSectionResponse',
  full_name='fkhp.page.layer.response.pmp.ReorderSectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='fkhp.page.layer.response.pmp.ReorderSectionResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sectionId', full_name='fkhp.page.layer.response.pmp.ReorderSectionResponse.sectionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newOrder', full_name='fkhp.page.layer.response.pmp.ReorderSectionResponse.newOrder', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['ReorderSectionResponse'] = _REORDERSECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReorderSectionResponse = _reflection.GeneratedProtocolMessageType('ReorderSectionResponse', (_message.Message,), dict(
  DESCRIPTOR = _REORDERSECTIONRESPONSE,
  __module__ = 'page.response.pmp.ReorderSectionResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.page.layer.response.pmp.ReorderSectionResponse)
  ))
_sym_db.RegisterMessage(ReorderSectionResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
