# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/request/pmp/FetchUiComponentMetaDataRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/request/pmp/FetchUiComponentMetaDataRequest.proto',
  package='fkhp.page.layer.request.pmp',
  syntax='proto3',
  serialized_options=_b('\n\033fkhp.page.layer.request.pmpP\001'),
  serialized_pb=_b('\n6page/request/pmp/FetchUiComponentMetaDataRequest.proto\x12\x1b\x66khp.page.layer.request.pmp\"8\n\x1f\x46\x65tchUiComponentMetaDataRequest\x12\x15\n\ruiComponentId\x18\x01 \x01(\tB\x1f\n\x1b\x66khp.page.layer.request.pmpP\x01\x62\x06proto3')
)




_FETCHUICOMPONENTMETADATAREQUEST = _descriptor.Descriptor(
  name='FetchUiComponentMetaDataRequest',
  full_name='fkhp.page.layer.request.pmp.FetchUiComponentMetaDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uiComponentId', full_name='fkhp.page.layer.request.pmp.FetchUiComponentMetaDataRequest.uiComponentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['FetchUiComponentMetaDataRequest'] = _FETCHUICOMPONENTMETADATAREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FetchUiComponentMetaDataRequest = _reflection.GeneratedProtocolMessageType('FetchUiComponentMetaDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _FETCHUICOMPONENTMETADATAREQUEST,
  __module__ = 'page.request.pmp.FetchUiComponentMetaDataRequest_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.page.layer.request.pmp.FetchUiComponentMetaDataRequest)
  ))
_sym_db.RegisterMessage(FetchUiComponentMetaDataRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
