# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/requests/UploadPrescriptionRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gateway.models import UploadPrescriptionFile_pb2 as gateway_dot_models_dot_UploadPrescriptionFile__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway/requests/UploadPrescriptionRequest.proto',
  package='fkhp.gateway.layer.client.requests',
  syntax='proto3',
  serialized_options=_b('\n\"fkhp.gateway.layer.client.requestsP\001'),
  serialized_pb=_b('\n0gateway/requests/UploadPrescriptionRequest.proto\x12\"fkhp.gateway.layer.client.requests\x1a+gateway/models/UploadPrescriptionFile.proto\"d\n\x19UploadPrescriptionRequest\x12G\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x38.fkhp.gateway.layer.client.models.UploadPrescriptionFileB&\n\"fkhp.gateway.layer.client.requestsP\x01\x62\x06proto3')
  ,
  dependencies=[gateway_dot_models_dot_UploadPrescriptionFile__pb2.DESCRIPTOR,])




_UPLOADPRESCRIPTIONREQUEST = _descriptor.Descriptor(
  name='UploadPrescriptionRequest',
  full_name='fkhp.gateway.layer.client.requests.UploadPrescriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='files', full_name='fkhp.gateway.layer.client.requests.UploadPrescriptionRequest.files', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=233,
)

_UPLOADPRESCRIPTIONREQUEST.fields_by_name['files'].message_type = gateway_dot_models_dot_UploadPrescriptionFile__pb2._UPLOADPRESCRIPTIONFILE
DESCRIPTOR.message_types_by_name['UploadPrescriptionRequest'] = _UPLOADPRESCRIPTIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadPrescriptionRequest = _reflection.GeneratedProtocolMessageType('UploadPrescriptionRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADPRESCRIPTIONREQUEST,
  __module__ = 'gateway.requests.UploadPrescriptionRequest_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.gateway.layer.client.requests.UploadPrescriptionRequest)
  ))
_sym_db.RegisterMessage(UploadPrescriptionRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
