# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/AccountPageViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import userInfo_pb2 as executor_dot_models_dot_userInfo__pb2
from executor.models import statusInfo_pb2 as executor_dot_models_dot_statusInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/AccountPageViewResponse.proto',
  package='fkhp.data.layer.executor.response',
  syntax='proto3',
  serialized_options=_b('\n!fkhp.data.layer.executor.responseP\001'),
  serialized_pb=_b('\n/executor/response/AccountPageViewResponse.proto\x12!fkhp.data.layer.executor.response\x1a\x1e\x65xecutor/models/userInfo.proto\x1a executor/models/statusInfo.proto\"\xda\x01\n\x17\x41\x63\x63ountPageViewResponse\x12?\n\nstatusInfo\x18\x01 \x01(\x0b\x32+.fkhp.data.layer.executor.models.StatusInfo\x12=\n\nuserDetail\x18\x02 \x01(\x0b\x32).fkhp.data.layer.executor.models.UserInfo\x12\x14\n\x0ctotalSavings\x18\x03 \x01(\t\x12\x12\n\norderCount\x18\x04 \x01(\t\x12\x15\n\rwalletBalance\x18\x05 \x01(\tB%\n!fkhp.data.layer.executor.responseP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_userInfo__pb2.DESCRIPTOR,executor_dot_models_dot_statusInfo__pb2.DESCRIPTOR,])




_ACCOUNTPAGEVIEWRESPONSE = _descriptor.Descriptor(
  name='AccountPageViewResponse',
  full_name='fkhp.data.layer.executor.response.AccountPageViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusInfo', full_name='fkhp.data.layer.executor.response.AccountPageViewResponse.statusInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userDetail', full_name='fkhp.data.layer.executor.response.AccountPageViewResponse.userDetail', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalSavings', full_name='fkhp.data.layer.executor.response.AccountPageViewResponse.totalSavings', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderCount', full_name='fkhp.data.layer.executor.response.AccountPageViewResponse.orderCount', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='walletBalance', full_name='fkhp.data.layer.executor.response.AccountPageViewResponse.walletBalance', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=371,
)

_ACCOUNTPAGEVIEWRESPONSE.fields_by_name['statusInfo'].message_type = executor_dot_models_dot_statusInfo__pb2._STATUSINFO
_ACCOUNTPAGEVIEWRESPONSE.fields_by_name['userDetail'].message_type = executor_dot_models_dot_userInfo__pb2._USERINFO
DESCRIPTOR.message_types_by_name['AccountPageViewResponse'] = _ACCOUNTPAGEVIEWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountPageViewResponse = _reflection.GeneratedProtocolMessageType('AccountPageViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTPAGEVIEWRESPONSE,
  __module__ = 'executor.response.AccountPageViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.AccountPageViewResponse)
  ))
_sym_db.RegisterMessage(AccountPageViewResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
