# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/AddressBookViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from executor.models import actionResponse_pb2 as executor_dot_models_dot_actionResponse__pb2
from executor.models import addressInfo_pb2 as executor_dot_models_dot_addressInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/AddressBookViewResponse.proto',
  package='fkhp.data.layer.executor.response',
  syntax='proto3',
  serialized_options=_b('\n!fkhp.data.layer.executor.responseP\001'),
  serialized_pb=_b('\n/executor/response/AddressBookViewResponse.proto\x12!fkhp.data.layer.executor.response\x1a\x19google/protobuf/any.proto\x1a$executor/models/actionResponse.proto\x1a!executor/models/addressInfo.proto\"\xb8\x01\n\x17\x41\x64\x64ressBookViewResponse\x12G\n\x0e\x61\x63tionResponse\x18\x01 \x01(\x0b\x32/.fkhp.data.layer.executor.models.ActionResponse\x12T\n\x0e\x64omainResponse\x18\x02 \x01(\x0b\x32<.fkhp.data.layer.executor.response.AddressBookDomainResponse\"^\n\x19\x41\x64\x64ressBookDomainResponse\x12\x41\n\x0b\x61\x64\x64ressList\x18\x02 \x03(\x0b\x32,.fkhp.data.layer.executor.models.AddressInfoB%\n!fkhp.data.layer.executor.responseP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,executor_dot_models_dot_actionResponse__pb2.DESCRIPTOR,executor_dot_models_dot_addressInfo__pb2.DESCRIPTOR,])




_ADDRESSBOOKVIEWRESPONSE = _descriptor.Descriptor(
  name='AddressBookViewResponse',
  full_name='fkhp.data.layer.executor.response.AddressBookViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actionResponse', full_name='fkhp.data.layer.executor.response.AddressBookViewResponse.actionResponse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domainResponse', full_name='fkhp.data.layer.executor.response.AddressBookViewResponse.domainResponse', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=371,
)


_ADDRESSBOOKDOMAINRESPONSE = _descriptor.Descriptor(
  name='AddressBookDomainResponse',
  full_name='fkhp.data.layer.executor.response.AddressBookDomainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addressList', full_name='fkhp.data.layer.executor.response.AddressBookDomainResponse.addressList', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=467,
)

_ADDRESSBOOKVIEWRESPONSE.fields_by_name['actionResponse'].message_type = executor_dot_models_dot_actionResponse__pb2._ACTIONRESPONSE
_ADDRESSBOOKVIEWRESPONSE.fields_by_name['domainResponse'].message_type = _ADDRESSBOOKDOMAINRESPONSE
_ADDRESSBOOKDOMAINRESPONSE.fields_by_name['addressList'].message_type = executor_dot_models_dot_addressInfo__pb2._ADDRESSINFO
DESCRIPTOR.message_types_by_name['AddressBookViewResponse'] = _ADDRESSBOOKVIEWRESPONSE
DESCRIPTOR.message_types_by_name['AddressBookDomainResponse'] = _ADDRESSBOOKDOMAINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressBookViewResponse = _reflection.GeneratedProtocolMessageType('AddressBookViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSBOOKVIEWRESPONSE,
  __module__ = 'executor.response.AddressBookViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.AddressBookViewResponse)
  ))
_sym_db.RegisterMessage(AddressBookViewResponse)

AddressBookDomainResponse = _reflection.GeneratedProtocolMessageType('AddressBookDomainResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSBOOKDOMAINRESPONSE,
  __module__ = 'executor.response.AddressBookViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.AddressBookDomainResponse)
  ))
_sym_db.RegisterMessage(AddressBookDomainResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
