# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/CategoryViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import multiMediaInfo_pb2 as executor_dot_models_dot_multiMediaInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/CategoryViewResponse.proto',
  package='fkhp.data.layer.executor.response',
  syntax='proto3',
  serialized_options=_b('\n!fkhp.data.layer.executor.responseP\001'),
  serialized_pb=_b('\n,executor/response/CategoryViewResponse.proto\x12!fkhp.data.layer.executor.response\x1a$executor/models/multiMediaInfo.proto\"t\n\x14\x43\x61tegoryViewResponse\x12\x45\n\x0c\x63\x61tegoryInfo\x18\x01 \x03(\x0b\x32/.fkhp.data.layer.executor.models.MultiMediaInfo\x12\x15\n\rcategoryTitle\x18\x02 \x01(\tB%\n!fkhp.data.layer.executor.responseP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_multiMediaInfo__pb2.DESCRIPTOR,])




_CATEGORYVIEWRESPONSE = _descriptor.Descriptor(
  name='CategoryViewResponse',
  full_name='fkhp.data.layer.executor.response.CategoryViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='categoryInfo', full_name='fkhp.data.layer.executor.response.CategoryViewResponse.categoryInfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categoryTitle', full_name='fkhp.data.layer.executor.response.CategoryViewResponse.categoryTitle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=237,
)

_CATEGORYVIEWRESPONSE.fields_by_name['categoryInfo'].message_type = executor_dot_models_dot_multiMediaInfo__pb2._MULTIMEDIAINFO
DESCRIPTOR.message_types_by_name['CategoryViewResponse'] = _CATEGORYVIEWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CategoryViewResponse = _reflection.GeneratedProtocolMessageType('CategoryViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _CATEGORYVIEWRESPONSE,
  __module__ = 'executor.response.CategoryViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.CategoryViewResponse)
  ))
_sym_db.RegisterMessage(CategoryViewResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
