# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/ChangePasswordViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import actionResponse_pb2 as executor_dot_models_dot_actionResponse__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/ChangePasswordViewResponse.proto',
  package='fkhp.data.layer.executor.response',
  syntax='proto3',
  serialized_options=_b('\n!fkhp.data.layer.executor.responseP\001'),
  serialized_pb=_b('\n2executor/response/ChangePasswordViewResponse.proto\x12!fkhp.data.layer.executor.response\x1a$executor/models/actionResponse.proto\"e\n\x1a\x43hangePasswordViewResponse\x12G\n\x0e\x61\x63tionResponse\x18\x03 \x01(\x0b\x32/.fkhp.data.layer.executor.models.ActionResponseB%\n!fkhp.data.layer.executor.responseP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_actionResponse__pb2.DESCRIPTOR,])




_CHANGEPASSWORDVIEWRESPONSE = _descriptor.Descriptor(
  name='ChangePasswordViewResponse',
  full_name='fkhp.data.layer.executor.response.ChangePasswordViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actionResponse', full_name='fkhp.data.layer.executor.response.ChangePasswordViewResponse.actionResponse', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=228,
)

_CHANGEPASSWORDVIEWRESPONSE.fields_by_name['actionResponse'].message_type = executor_dot_models_dot_actionResponse__pb2._ACTIONRESPONSE
DESCRIPTOR.message_types_by_name['ChangePasswordViewResponse'] = _CHANGEPASSWORDVIEWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChangePasswordViewResponse = _reflection.GeneratedProtocolMessageType('ChangePasswordViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHANGEPASSWORDVIEWRESPONSE,
  __module__ = 'executor.response.ChangePasswordViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.ChangePasswordViewResponse)
  ))
_sym_db.RegisterMessage(ChangePasswordViewResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
