# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/GetArticlesViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from executor.models import statusInfo_pb2 as executor_dot_models_dot_statusInfo__pb2
from executor.models import multiMediaInfo_pb2 as executor_dot_models_dot_multiMediaInfo__pb2
from executor.models import prescriptionDetailInfo_pb2 as executor_dot_models_dot_prescriptionDetailInfo__pb2
from executor.models import articleInfo_pb2 as executor_dot_models_dot_articleInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/GetArticlesViewResponse.proto',
  package='fkhp.data.layer.executor.response',
  syntax='proto3',
  serialized_options=_b('\n!fkhp.data.layer.executor.responseP\001'),
  serialized_pb=_b('\n/executor/response/GetArticlesViewResponse.proto\x12!fkhp.data.layer.executor.response\x1a\x19google/protobuf/any.proto\x1a executor/models/statusInfo.proto\x1a$executor/models/multiMediaInfo.proto\x1a,executor/models/prescriptionDetailInfo.proto\x1a!executor/models/articleInfo.proto\"\xb0\x01\n\x17GetArticlesViewResponse\x12?\n\nstatusInfo\x18\x01 \x01(\x0b\x32+.fkhp.data.layer.executor.models.StatusInfo\x12>\n\x08\x61rticles\x18\x02 \x03(\x0b\x32,.fkhp.data.layer.executor.models.ArticleInfo\x12\x14\n\x0c\x63\x61tegoryName\x18\x03 \x01(\tB%\n!fkhp.data.layer.executor.responseP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,executor_dot_models_dot_statusInfo__pb2.DESCRIPTOR,executor_dot_models_dot_multiMediaInfo__pb2.DESCRIPTOR,executor_dot_models_dot_prescriptionDetailInfo__pb2.DESCRIPTOR,executor_dot_models_dot_articleInfo__pb2.DESCRIPTOR,])




_GETARTICLESVIEWRESPONSE = _descriptor.Descriptor(
  name='GetArticlesViewResponse',
  full_name='fkhp.data.layer.executor.response.GetArticlesViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusInfo', full_name='fkhp.data.layer.executor.response.GetArticlesViewResponse.statusInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='articles', full_name='fkhp.data.layer.executor.response.GetArticlesViewResponse.articles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categoryName', full_name='fkhp.data.layer.executor.response.GetArticlesViewResponse.categoryName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=443,
)

_GETARTICLESVIEWRESPONSE.fields_by_name['statusInfo'].message_type = executor_dot_models_dot_statusInfo__pb2._STATUSINFO
_GETARTICLESVIEWRESPONSE.fields_by_name['articles'].message_type = executor_dot_models_dot_articleInfo__pb2._ARTICLEINFO
DESCRIPTOR.message_types_by_name['GetArticlesViewResponse'] = _GETARTICLESVIEWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetArticlesViewResponse = _reflection.GeneratedProtocolMessageType('GetArticlesViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETARTICLESVIEWRESPONSE,
  __module__ = 'executor.response.GetArticlesViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.GetArticlesViewResponse)
  ))
_sym_db.RegisterMessage(GetArticlesViewResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
