# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/PrescriptionPageViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from executor.models import statusInfo_pb2 as executor_dot_models_dot_statusInfo__pb2
from executor.models import nearestAreaInfo_pb2 as executor_dot_models_dot_nearestAreaInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/PrescriptionPageViewResponse.proto',
  package='fkhp.data.layer.executor.response',
  syntax='proto3',
  serialized_options=_b('\n!fkhp.data.layer.executor.responseP\001'),
  serialized_pb=_b('\n4executor/response/PrescriptionPageViewResponse.proto\x12!fkhp.data.layer.executor.response\x1a\x19google/protobuf/any.proto\x1a executor/models/statusInfo.proto\x1a%executor/models/nearestAreaInfo.proto\"R\n\x1cPrescriptionPageViewResponse\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x10\n\x08imageUrl\x18\x02 \x01(\t\x12\x0b\n\x03ttl\x18\x03 \x01(\tB%\n!fkhp.data.layer.executor.responseP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,executor_dot_models_dot_statusInfo__pb2.DESCRIPTOR,executor_dot_models_dot_nearestAreaInfo__pb2.DESCRIPTOR,])




_PRESCRIPTIONPAGEVIEWRESPONSE = _descriptor.Descriptor(
  name='PrescriptionPageViewResponse',
  full_name='fkhp.data.layer.executor.response.PrescriptionPageViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='fkhp.data.layer.executor.response.PrescriptionPageViewResponse.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='fkhp.data.layer.executor.response.PrescriptionPageViewResponse.imageUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='fkhp.data.layer.executor.response.PrescriptionPageViewResponse.ttl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=273,
)

DESCRIPTOR.message_types_by_name['PrescriptionPageViewResponse'] = _PRESCRIPTIONPAGEVIEWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrescriptionPageViewResponse = _reflection.GeneratedProtocolMessageType('PrescriptionPageViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _PRESCRIPTIONPAGEVIEWRESPONSE,
  __module__ = 'executor.response.PrescriptionPageViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.PrescriptionPageViewResponse)
  ))
_sym_db.RegisterMessage(PrescriptionPageViewResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
