# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/ReturnMediumListViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import statusInfo_pb2 as executor_dot_models_dot_statusInfo__pb2
from executor.models import actionResponse_pb2 as executor_dot_models_dot_actionResponse__pb2
from executor.models import returnMediumType_pb2 as executor_dot_models_dot_returnMediumType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/ReturnMediumListViewResponse.proto',
  package='fkhp.data.layer.executor.response',
  syntax='proto3',
  serialized_options=_b('\n!fkhp.data.layer.executor.responseP\001'),
  serialized_pb=_b('\n4executor/response/ReturnMediumListViewResponse.proto\x12!fkhp.data.layer.executor.response\x1a executor/models/statusInfo.proto\x1a$executor/models/actionResponse.proto\x1a&executor/models/returnMediumType.proto\"\xb8\x01\n\x1cReturnMediumListViewResponse\x12G\n\x0e\x61\x63tionResponse\x18\x01 \x01(\x0b\x32/.fkhp.data.layer.executor.models.ActionResponse\x12O\n\x0e\x64omainResponse\x18\x02 \x01(\x0b\x32\x37.fkhp.data.layer.executor.response.ReturnMediumListInfo\"\xcc\x01\n\x14ReturnMediumListInfo\x12\x14\n\x0crefundAmount\x18\x01 \x01(\x01\x12M\n\x10\x62\x61nkRecordParams\x18\x02 \x01(\x0b\x32\x33.fkhp.data.layer.executor.response.BankRecordParams\x12O\n\x12return_medium_list\x18\x03 \x03(\x0b\x32\x33.fkhp.data.layer.executor.response.ReturnMediumList\"H\n\x10\x42\x61nkRecordParams\x12\x13\n\x0b\x41\x63\x63ountName\x18\x01 \x01(\t\x12\x11\n\tAccountNo\x18\x02 \x01(\t\x12\x0c\n\x04Ifsc\x18\x03 \x01(\t\"\xa8\x01\n\x10ReturnMediumList\x12\n\n\x02Id\x18\x01 \x01(\t\x12\x11\n\tIsDefault\x18\x02 \x01(\x08\x12\r\n\x05Title\x18\x03 \x01(\t\x12\x0b\n\x03TTL\x18\x04 \x01(\t\x12\x0c\n\x04Text\x18\x05 \x01(\t\x12K\n\x10returnMediumType\x18\x06 \x01(\x0e\x32\x31.fkhp.data.layer.executor.models.ReturnMediumTypeB%\n!fkhp.data.layer.executor.responseP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_statusInfo__pb2.DESCRIPTOR,executor_dot_models_dot_actionResponse__pb2.DESCRIPTOR,executor_dot_models_dot_returnMediumType__pb2.DESCRIPTOR,])




_RETURNMEDIUMLISTVIEWRESPONSE = _descriptor.Descriptor(
  name='ReturnMediumListViewResponse',
  full_name='fkhp.data.layer.executor.response.ReturnMediumListViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actionResponse', full_name='fkhp.data.layer.executor.response.ReturnMediumListViewResponse.actionResponse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domainResponse', full_name='fkhp.data.layer.executor.response.ReturnMediumListViewResponse.domainResponse', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=388,
)


_RETURNMEDIUMLISTINFO = _descriptor.Descriptor(
  name='ReturnMediumListInfo',
  full_name='fkhp.data.layer.executor.response.ReturnMediumListInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='refundAmount', full_name='fkhp.data.layer.executor.response.ReturnMediumListInfo.refundAmount', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bankRecordParams', full_name='fkhp.data.layer.executor.response.ReturnMediumListInfo.bankRecordParams', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_medium_list', full_name='fkhp.data.layer.executor.response.ReturnMediumListInfo.return_medium_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=595,
)


_BANKRECORDPARAMS = _descriptor.Descriptor(
  name='BankRecordParams',
  full_name='fkhp.data.layer.executor.response.BankRecordParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccountName', full_name='fkhp.data.layer.executor.response.BankRecordParams.AccountName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AccountNo', full_name='fkhp.data.layer.executor.response.BankRecordParams.AccountNo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Ifsc', full_name='fkhp.data.layer.executor.response.BankRecordParams.Ifsc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=669,
)


_RETURNMEDIUMLIST = _descriptor.Descriptor(
  name='ReturnMediumList',
  full_name='fkhp.data.layer.executor.response.ReturnMediumList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='fkhp.data.layer.executor.response.ReturnMediumList.Id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IsDefault', full_name='fkhp.data.layer.executor.response.ReturnMediumList.IsDefault', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Title', full_name='fkhp.data.layer.executor.response.ReturnMediumList.Title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TTL', full_name='fkhp.data.layer.executor.response.ReturnMediumList.TTL', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Text', full_name='fkhp.data.layer.executor.response.ReturnMediumList.Text', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returnMediumType', full_name='fkhp.data.layer.executor.response.ReturnMediumList.returnMediumType', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=672,
  serialized_end=840,
)

_RETURNMEDIUMLISTVIEWRESPONSE.fields_by_name['actionResponse'].message_type = executor_dot_models_dot_actionResponse__pb2._ACTIONRESPONSE
_RETURNMEDIUMLISTVIEWRESPONSE.fields_by_name['domainResponse'].message_type = _RETURNMEDIUMLISTINFO
_RETURNMEDIUMLISTINFO.fields_by_name['bankRecordParams'].message_type = _BANKRECORDPARAMS
_RETURNMEDIUMLISTINFO.fields_by_name['return_medium_list'].message_type = _RETURNMEDIUMLIST
_RETURNMEDIUMLIST.fields_by_name['returnMediumType'].enum_type = executor_dot_models_dot_returnMediumType__pb2._RETURNMEDIUMTYPE
DESCRIPTOR.message_types_by_name['ReturnMediumListViewResponse'] = _RETURNMEDIUMLISTVIEWRESPONSE
DESCRIPTOR.message_types_by_name['ReturnMediumListInfo'] = _RETURNMEDIUMLISTINFO
DESCRIPTOR.message_types_by_name['BankRecordParams'] = _BANKRECORDPARAMS
DESCRIPTOR.message_types_by_name['ReturnMediumList'] = _RETURNMEDIUMLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReturnMediumListViewResponse = _reflection.GeneratedProtocolMessageType('ReturnMediumListViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _RETURNMEDIUMLISTVIEWRESPONSE,
  __module__ = 'executor.response.ReturnMediumListViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.ReturnMediumListViewResponse)
  ))
_sym_db.RegisterMessage(ReturnMediumListViewResponse)

ReturnMediumListInfo = _reflection.GeneratedProtocolMessageType('ReturnMediumListInfo', (_message.Message,), dict(
  DESCRIPTOR = _RETURNMEDIUMLISTINFO,
  __module__ = 'executor.response.ReturnMediumListViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.ReturnMediumListInfo)
  ))
_sym_db.RegisterMessage(ReturnMediumListInfo)

BankRecordParams = _reflection.GeneratedProtocolMessageType('BankRecordParams', (_message.Message,), dict(
  DESCRIPTOR = _BANKRECORDPARAMS,
  __module__ = 'executor.response.ReturnMediumListViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.BankRecordParams)
  ))
_sym_db.RegisterMessage(BankRecordParams)

ReturnMediumList = _reflection.GeneratedProtocolMessageType('ReturnMediumList', (_message.Message,), dict(
  DESCRIPTOR = _RETURNMEDIUMLIST,
  __module__ = 'executor.response.ReturnMediumListViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.ReturnMediumList)
  ))
_sym_db.RegisterMessage(ReturnMediumList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
