# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/ReturnReasonsViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import actionResponse_pb2 as executor_dot_models_dot_actionResponse__pb2
from executor.models import priceInfo_pb2 as executor_dot_models_dot_priceInfo__pb2
from executor.models import multiMediaInfo_pb2 as executor_dot_models_dot_multiMediaInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/ReturnReasonsViewResponse.proto',
  package='fkhp.data.layer.executor.response',
  syntax='proto3',
  serialized_options=_b('\n!fkhp.data.layer.executor.responseP\001'),
  serialized_pb=_b('\n1executor/response/ReturnReasonsViewResponse.proto\x12!fkhp.data.layer.executor.response\x1a$executor/models/actionResponse.proto\x1a\x1f\x65xecutor/models/priceInfo.proto\x1a$executor/models/multiMediaInfo.proto\"\xbc\x01\n\x19ReturnReasonsViewResponse\x12G\n\x0e\x61\x63tionResponse\x18\x01 \x01(\x0b\x32/.fkhp.data.layer.executor.models.ActionResponse\x12V\n\x0e\x64omainResponse\x18\x02 \x01(\x0b\x32>.fkhp.data.layer.executor.response.ReturnReasonsDomainResponse\"\x9b\x02\n\x1bReturnReasonsDomainResponse\x12\x45\n\x07reasons\x18\x02 \x03(\x0b\x32\x34.fkhp.data.layer.executor.response.ReturnReasonsList\x12\x11\n\tinvoiceNo\x18\x03 \x01(\t\x12\x11\n\tinvoiceId\x18\x04 \x01(\t\x12\x0f\n\x07orderId\x18\x05 \x01(\t\x12\x17\n\x0forderBillAmount\x18\x06 \x01(\t\x12\x11\n\torderDate\x18\x07 \x01(\t\x12R\n\x14returnProductDetails\x18\x08 \x03(\x0b\x32\x34.fkhp.data.layer.executor.response.ReturnProductInfo\".\n\x11ReturnReasonsList\x12\r\n\x05value\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"\xdc\x03\n\x11ReturnProductInfo\x12\x13\n\x0bproductName\x18\x01 \x01(\t\x12\x12\n\nexpiryDate\x18\x02 \x01(\t\x12\x15\n\rinvoiceItemId\x18\x03 \x01(\t\x12\x12\n\ninvoiceVal\x18\x04 \x01(\x01\x12\x17\n\x0fisNonReturnable\x18\x05 \x01(\x08\x12\x1d\n\x15isNonReturnableForApp\x18\x06 \x01(\x08\x12\x12\n\nitemCoupon\x18\x07 \x01(\x01\x12\x14\n\x0citemDiscount\x18\x08 \x01(\x01\x12=\n\tpriceInfo\x18\t \x01(\x0b\x32*.fkhp.data.layer.executor.models.PriceInfo\x12\x17\n\x0forderedQuantity\x18\n \x01(\x05\x12\x17\n\x0fprevReturnedQty\x18\x0b \x01(\x05\x12>\n\x05image\x18\x0c \x01(\x0b\x32/.fkhp.data.layer.executor.models.MultiMediaInfo\x12\x1b\n\x13salesReturnQuantity\x18\r \x01(\x05\x12\x17\n\x0fperItemDiscount\x18\x0e \x01(\x01\x12\x14\n\x0cheaderCoupon\x18\x0f \x01(\t\x12\x14\n\x0creturnMedium\x18\x10 \x01(\tB%\n!fkhp.data.layer.executor.responseP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_actionResponse__pb2.DESCRIPTOR,executor_dot_models_dot_priceInfo__pb2.DESCRIPTOR,executor_dot_models_dot_multiMediaInfo__pb2.DESCRIPTOR,])




_RETURNREASONSVIEWRESPONSE = _descriptor.Descriptor(
  name='ReturnReasonsViewResponse',
  full_name='fkhp.data.layer.executor.response.ReturnReasonsViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actionResponse', full_name='fkhp.data.layer.executor.response.ReturnReasonsViewResponse.actionResponse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domainResponse', full_name='fkhp.data.layer.executor.response.ReturnReasonsViewResponse.domainResponse', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=386,
)


_RETURNREASONSDOMAINRESPONSE = _descriptor.Descriptor(
  name='ReturnReasonsDomainResponse',
  full_name='fkhp.data.layer.executor.response.ReturnReasonsDomainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reasons', full_name='fkhp.data.layer.executor.response.ReturnReasonsDomainResponse.reasons', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='invoiceNo', full_name='fkhp.data.layer.executor.response.ReturnReasonsDomainResponse.invoiceNo', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='invoiceId', full_name='fkhp.data.layer.executor.response.ReturnReasonsDomainResponse.invoiceId', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderId', full_name='fkhp.data.layer.executor.response.ReturnReasonsDomainResponse.orderId', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderBillAmount', full_name='fkhp.data.layer.executor.response.ReturnReasonsDomainResponse.orderBillAmount', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderDate', full_name='fkhp.data.layer.executor.response.ReturnReasonsDomainResponse.orderDate', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returnProductDetails', full_name='fkhp.data.layer.executor.response.ReturnReasonsDomainResponse.returnProductDetails', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=672,
)


_RETURNREASONSLIST = _descriptor.Descriptor(
  name='ReturnReasonsList',
  full_name='fkhp.data.layer.executor.response.ReturnReasonsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='fkhp.data.layer.executor.response.ReturnReasonsList.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='fkhp.data.layer.executor.response.ReturnReasonsList.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=674,
  serialized_end=720,
)


_RETURNPRODUCTINFO = _descriptor.Descriptor(
  name='ReturnProductInfo',
  full_name='fkhp.data.layer.executor.response.ReturnProductInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productName', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.productName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiryDate', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.expiryDate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='invoiceItemId', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.invoiceItemId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='invoiceVal', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.invoiceVal', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isNonReturnable', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.isNonReturnable', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isNonReturnableForApp', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.isNonReturnableForApp', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itemCoupon', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.itemCoupon', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itemDiscount', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.itemDiscount', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priceInfo', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.priceInfo', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderedQuantity', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.orderedQuantity', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prevReturnedQty', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.prevReturnedQty', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.image', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='salesReturnQuantity', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.salesReturnQuantity', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='perItemDiscount', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.perItemDiscount', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headerCoupon', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.headerCoupon', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returnMedium', full_name='fkhp.data.layer.executor.response.ReturnProductInfo.returnMedium', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=723,
  serialized_end=1199,
)

_RETURNREASONSVIEWRESPONSE.fields_by_name['actionResponse'].message_type = executor_dot_models_dot_actionResponse__pb2._ACTIONRESPONSE
_RETURNREASONSVIEWRESPONSE.fields_by_name['domainResponse'].message_type = _RETURNREASONSDOMAINRESPONSE
_RETURNREASONSDOMAINRESPONSE.fields_by_name['reasons'].message_type = _RETURNREASONSLIST
_RETURNREASONSDOMAINRESPONSE.fields_by_name['returnProductDetails'].message_type = _RETURNPRODUCTINFO
_RETURNPRODUCTINFO.fields_by_name['priceInfo'].message_type = executor_dot_models_dot_priceInfo__pb2._PRICEINFO
_RETURNPRODUCTINFO.fields_by_name['image'].message_type = executor_dot_models_dot_multiMediaInfo__pb2._MULTIMEDIAINFO
DESCRIPTOR.message_types_by_name['ReturnReasonsViewResponse'] = _RETURNREASONSVIEWRESPONSE
DESCRIPTOR.message_types_by_name['ReturnReasonsDomainResponse'] = _RETURNREASONSDOMAINRESPONSE
DESCRIPTOR.message_types_by_name['ReturnReasonsList'] = _RETURNREASONSLIST
DESCRIPTOR.message_types_by_name['ReturnProductInfo'] = _RETURNPRODUCTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReturnReasonsViewResponse = _reflection.GeneratedProtocolMessageType('ReturnReasonsViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _RETURNREASONSVIEWRESPONSE,
  __module__ = 'executor.response.ReturnReasonsViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.ReturnReasonsViewResponse)
  ))
_sym_db.RegisterMessage(ReturnReasonsViewResponse)

ReturnReasonsDomainResponse = _reflection.GeneratedProtocolMessageType('ReturnReasonsDomainResponse', (_message.Message,), dict(
  DESCRIPTOR = _RETURNREASONSDOMAINRESPONSE,
  __module__ = 'executor.response.ReturnReasonsViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.ReturnReasonsDomainResponse)
  ))
_sym_db.RegisterMessage(ReturnReasonsDomainResponse)

ReturnReasonsList = _reflection.GeneratedProtocolMessageType('ReturnReasonsList', (_message.Message,), dict(
  DESCRIPTOR = _RETURNREASONSLIST,
  __module__ = 'executor.response.ReturnReasonsViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.ReturnReasonsList)
  ))
_sym_db.RegisterMessage(ReturnReasonsList)

ReturnProductInfo = _reflection.GeneratedProtocolMessageType('ReturnProductInfo', (_message.Message,), dict(
  DESCRIPTOR = _RETURNPRODUCTINFO,
  __module__ = 'executor.response.ReturnReasonsViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.ReturnProductInfo)
  ))
_sym_db.RegisterMessage(ReturnProductInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
