# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/TeleConsultationViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from executor.models import addressInfo_pb2 as executor_dot_models_dot_addressInfo__pb2
from executor.models import actionResponse_pb2 as executor_dot_models_dot_actionResponse__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/TeleConsultationViewResponse.proto',
  package='fkhp.data.layer.executor.response',
  syntax='proto3',
  serialized_options=_b('\n!fkhp.data.layer.executor.responseP\001'),
  serialized_pb=_b('\n4executor/response/TeleConsultationViewResponse.proto\x12!fkhp.data.layer.executor.response\x1a\x19google/protobuf/any.proto\x1a!executor/models/addressInfo.proto\x1a$executor/models/actionResponse.proto\"\xc2\x01\n\x1cTeleConsultationViewResponse\x12G\n\x0e\x61\x63tionResponse\x18\x01 \x01(\x0b\x32/.fkhp.data.layer.executor.models.ActionResponse\x12Y\n\x0e\x64omainResponse\x18\x02 \x01(\x0b\x32\x41.fkhp.data.layer.executor.response.TeleConsultationDomainResponse\"\x88\x01\n\x1eTeleConsultationDomainResponse\x12\x13\n\x0b\x64octorImage\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nshowStatus\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63tiveStatus\x18\x04 \x01(\t\x12\x12\n\ntimeToLive\x18\x05 \x01(\tB%\n!fkhp.data.layer.executor.responseP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,executor_dot_models_dot_addressInfo__pb2.DESCRIPTOR,executor_dot_models_dot_actionResponse__pb2.DESCRIPTOR,])




_TELECONSULTATIONVIEWRESPONSE = _descriptor.Descriptor(
  name='TeleConsultationViewResponse',
  full_name='fkhp.data.layer.executor.response.TeleConsultationViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actionResponse', full_name='fkhp.data.layer.executor.response.TeleConsultationViewResponse.actionResponse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domainResponse', full_name='fkhp.data.layer.executor.response.TeleConsultationViewResponse.domainResponse', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=386,
)


_TELECONSULTATIONDOMAINRESPONSE = _descriptor.Descriptor(
  name='TeleConsultationDomainResponse',
  full_name='fkhp.data.layer.executor.response.TeleConsultationDomainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doctorImage', full_name='fkhp.data.layer.executor.response.TeleConsultationDomainResponse.doctorImage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='fkhp.data.layer.executor.response.TeleConsultationDomainResponse.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='showStatus', full_name='fkhp.data.layer.executor.response.TeleConsultationDomainResponse.showStatus', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activeStatus', full_name='fkhp.data.layer.executor.response.TeleConsultationDomainResponse.activeStatus', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeToLive', full_name='fkhp.data.layer.executor.response.TeleConsultationDomainResponse.timeToLive', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=525,
)

_TELECONSULTATIONVIEWRESPONSE.fields_by_name['actionResponse'].message_type = executor_dot_models_dot_actionResponse__pb2._ACTIONRESPONSE
_TELECONSULTATIONVIEWRESPONSE.fields_by_name['domainResponse'].message_type = _TELECONSULTATIONDOMAINRESPONSE
DESCRIPTOR.message_types_by_name['TeleConsultationViewResponse'] = _TELECONSULTATIONVIEWRESPONSE
DESCRIPTOR.message_types_by_name['TeleConsultationDomainResponse'] = _TELECONSULTATIONDOMAINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeleConsultationViewResponse = _reflection.GeneratedProtocolMessageType('TeleConsultationViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _TELECONSULTATIONVIEWRESPONSE,
  __module__ = 'executor.response.TeleConsultationViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.TeleConsultationViewResponse)
  ))
_sym_db.RegisterMessage(TeleConsultationViewResponse)

TeleConsultationDomainResponse = _reflection.GeneratedProtocolMessageType('TeleConsultationDomainResponse', (_message.Message,), dict(
  DESCRIPTOR = _TELECONSULTATIONDOMAINRESPONSE,
  __module__ = 'executor.response.TeleConsultationViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.TeleConsultationDomainResponse)
  ))
_sym_db.RegisterMessage(TeleConsultationDomainResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
