# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/VerifyOtpViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import actionResponse_pb2 as executor_dot_models_dot_actionResponse__pb2
from executor.models import userInfo_pb2 as executor_dot_models_dot_userInfo__pb2
from executor.models import userPivots_pb2 as executor_dot_models_dot_userPivots__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/VerifyOtpViewResponse.proto',
  package='fkhp.data.layer.executor.request',
  syntax='proto3',
  serialized_options=_b('\n fkhp.data.layer.executor.requestP\001'),
  serialized_pb=_b('\n-executor/response/VerifyOtpViewResponse.proto\x12 fkhp.data.layer.executor.request\x1a$executor/models/actionResponse.proto\x1a\x1e\x65xecutor/models/userInfo.proto\x1a executor/models/userPivots.proto\"\xb3\x01\n\x15VerifyOtpViewResponse\x12G\n\x0e\x61\x63tionResponse\x18\x01 \x01(\x0b\x32/.fkhp.data.layer.executor.models.ActionResponse\x12Q\n\x0e\x64omainResponse\x18\x02 \x01(\x0b\x32\x39.fkhp.data.layer.executor.request.VerifyOtpDomainResponse\"\xae\x01\n\x17VerifyOtpDomainResponse\x12?\n\nuserPivots\x18\x01 \x01(\x0b\x32+.fkhp.data.layer.executor.models.UserPivots\x12;\n\x08userInfo\x18\x02 \x01(\x0b\x32).fkhp.data.layer.executor.models.UserInfo\x12\x15\n\rencodedUserId\x18\x03 \x01(\tB$\n fkhp.data.layer.executor.requestP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_actionResponse__pb2.DESCRIPTOR,executor_dot_models_dot_userInfo__pb2.DESCRIPTOR,executor_dot_models_dot_userPivots__pb2.DESCRIPTOR,])




_VERIFYOTPVIEWRESPONSE = _descriptor.Descriptor(
  name='VerifyOtpViewResponse',
  full_name='fkhp.data.layer.executor.request.VerifyOtpViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actionResponse', full_name='fkhp.data.layer.executor.request.VerifyOtpViewResponse.actionResponse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domainResponse', full_name='fkhp.data.layer.executor.request.VerifyOtpViewResponse.domainResponse', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=367,
)


_VERIFYOTPDOMAINRESPONSE = _descriptor.Descriptor(
  name='VerifyOtpDomainResponse',
  full_name='fkhp.data.layer.executor.request.VerifyOtpDomainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userPivots', full_name='fkhp.data.layer.executor.request.VerifyOtpDomainResponse.userPivots', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='fkhp.data.layer.executor.request.VerifyOtpDomainResponse.userInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encodedUserId', full_name='fkhp.data.layer.executor.request.VerifyOtpDomainResponse.encodedUserId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=544,
)

_VERIFYOTPVIEWRESPONSE.fields_by_name['actionResponse'].message_type = executor_dot_models_dot_actionResponse__pb2._ACTIONRESPONSE
_VERIFYOTPVIEWRESPONSE.fields_by_name['domainResponse'].message_type = _VERIFYOTPDOMAINRESPONSE
_VERIFYOTPDOMAINRESPONSE.fields_by_name['userPivots'].message_type = executor_dot_models_dot_userPivots__pb2._USERPIVOTS
_VERIFYOTPDOMAINRESPONSE.fields_by_name['userInfo'].message_type = executor_dot_models_dot_userInfo__pb2._USERINFO
DESCRIPTOR.message_types_by_name['VerifyOtpViewResponse'] = _VERIFYOTPVIEWRESPONSE
DESCRIPTOR.message_types_by_name['VerifyOtpDomainResponse'] = _VERIFYOTPDOMAINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerifyOtpViewResponse = _reflection.GeneratedProtocolMessageType('VerifyOtpViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYOTPVIEWRESPONSE,
  __module__ = 'executor.response.VerifyOtpViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.request.VerifyOtpViewResponse)
  ))
_sym_db.RegisterMessage(VerifyOtpViewResponse)

VerifyOtpDomainResponse = _reflection.GeneratedProtocolMessageType('VerifyOtpDomainResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYOTPDOMAINRESPONSE,
  __module__ = 'executor.response.VerifyOtpViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.request.VerifyOtpDomainResponse)
  ))
_sym_db.RegisterMessage(VerifyOtpDomainResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
