# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/response/WalletBalanceViewResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import statusInfo_pb2 as executor_dot_models_dot_statusInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/response/WalletBalanceViewResponse.proto',
  package='fkhp.data.layer.executor.response',
  syntax='proto3',
  serialized_options=_b('\n!fkhp.data.layer.executor.responseP\001'),
  serialized_pb=_b('\n1executor/response/WalletBalanceViewResponse.proto\x12!fkhp.data.layer.executor.response\x1a executor/models/statusInfo.proto\"m\n\x19WalletBalanceViewResponse\x12?\n\nstatusInfo\x18\x01 \x01(\x0b\x32+.fkhp.data.layer.executor.models.StatusInfo\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\tB%\n!fkhp.data.layer.executor.responseP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_statusInfo__pb2.DESCRIPTOR,])




_WALLETBALANCEVIEWRESPONSE = _descriptor.Descriptor(
  name='WalletBalanceViewResponse',
  full_name='fkhp.data.layer.executor.response.WalletBalanceViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusInfo', full_name='fkhp.data.layer.executor.response.WalletBalanceViewResponse.statusInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='fkhp.data.layer.executor.response.WalletBalanceViewResponse.balance', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=231,
)

_WALLETBALANCEVIEWRESPONSE.fields_by_name['statusInfo'].message_type = executor_dot_models_dot_statusInfo__pb2._STATUSINFO
DESCRIPTOR.message_types_by_name['WalletBalanceViewResponse'] = _WALLETBALANCEVIEWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WalletBalanceViewResponse = _reflection.GeneratedProtocolMessageType('WalletBalanceViewResponse', (_message.Message,), dict(
  DESCRIPTOR = _WALLETBALANCEVIEWRESPONSE,
  __module__ = 'executor.response.WalletBalanceViewResponse_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.response.WalletBalanceViewResponse)
  ))
_sym_db.RegisterMessage(WalletBalanceViewResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
