# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/models/page/pmp/PageUserInputModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from page.models.page.pmp import PageModelVersion_pb2 as page_dot_models_dot_page_dot_pmp_dot_PageModelVersion__pb2
from page.models.design.pmp import DesignParameter_pb2 as page_dot_models_dot_design_dot_pmp_dot_DesignParameter__pb2
from page.models.section.pmp import PageSectionUserInputModel_pb2 as page_dot_models_dot_section_dot_pmp_dot_PageSectionUserInputModel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/models/page/pmp/PageUserInputModel.proto',
  package='fkhp.page.layer.models.page.pmp',
  syntax='proto3',
  serialized_options=_b('\n\037fkhp.page.layer.models.page.pmpP\001'),
  serialized_pb=_b('\n-page/models/page/pmp/PageUserInputModel.proto\x12\x1f\x66khp.page.layer.models.page.pmp\x1a+page/models/page/pmp/PageModelVersion.proto\x1a,page/models/design/pmp/DesignParameter.proto\x1a\x37page/models/section/pmp/PageSectionUserInputModel.proto\"\x87\x02\n\x12PageUserInputModel\x12\x0e\n\x06pageId\x18\x01 \x01(\t\x12L\n\x10\x64\x65signParameters\x18\x02 \x03(\x0b\x32\x32.fkhp.page.layer.models.design.pmp.DesignParameter\x12O\n\x08sections\x18\x03 \x03(\x0b\x32=.fkhp.page.layer.models.section.pmp.PageSectionUserInputModel\x12\x42\n\x07version\x18\x04 \x01(\x0b\x32\x31.fkhp.page.layer.models.page.pmp.PageModelVersionB#\n\x1f\x66khp.page.layer.models.page.pmpP\x01\x62\x06proto3')
  ,
  dependencies=[page_dot_models_dot_page_dot_pmp_dot_PageModelVersion__pb2.DESCRIPTOR,page_dot_models_dot_design_dot_pmp_dot_DesignParameter__pb2.DESCRIPTOR,page_dot_models_dot_section_dot_pmp_dot_PageSectionUserInputModel__pb2.DESCRIPTOR,])




_PAGEUSERINPUTMODEL = _descriptor.Descriptor(
  name='PageUserInputModel',
  full_name='fkhp.page.layer.models.page.pmp.PageUserInputModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pageId', full_name='fkhp.page.layer.models.page.pmp.PageUserInputModel.pageId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='designParameters', full_name='fkhp.page.layer.models.page.pmp.PageUserInputModel.designParameters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sections', full_name='fkhp.page.layer.models.page.pmp.PageUserInputModel.sections', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='fkhp.page.layer.models.page.pmp.PageUserInputModel.version', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=494,
)

_PAGEUSERINPUTMODEL.fields_by_name['designParameters'].message_type = page_dot_models_dot_design_dot_pmp_dot_DesignParameter__pb2._DESIGNPARAMETER
_PAGEUSERINPUTMODEL.fields_by_name['sections'].message_type = page_dot_models_dot_section_dot_pmp_dot_PageSectionUserInputModel__pb2._PAGESECTIONUSERINPUTMODEL
_PAGEUSERINPUTMODEL.fields_by_name['version'].message_type = page_dot_models_dot_page_dot_pmp_dot_PageModelVersion__pb2._PAGEMODELVERSION
DESCRIPTOR.message_types_by_name['PageUserInputModel'] = _PAGEUSERINPUTMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PageUserInputModel = _reflection.GeneratedProtocolMessageType('PageUserInputModel', (_message.Message,), dict(
  DESCRIPTOR = _PAGEUSERINPUTMODEL,
  __module__ = 'page.models.page.pmp.PageUserInputModel_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.page.layer.models.page.pmp.PageUserInputModel)
  ))
_sym_db.RegisterMessage(PageUserInputModel)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
