# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/models/element/FilterContext.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/models/element/FilterContext.proto',
  package='fkhp.page.layer.models.element',
  syntax='proto3',
  serialized_options=_b('\n\036fkhp.page.layer.models.elementP\001'),
  serialized_pb=_b('\n\'page/models/element/FilterContext.proto\x12\x1e\x66khp.page.layer.models.element\"7\n\rFilterContext\x12\x11\n\tfilterKey\x18\x01 \x01(\t\x12\x13\n\x0b\x66ilterValue\x18\x02 \x03(\tB\"\n\x1e\x66khp.page.layer.models.elementP\x01\x62\x06proto3')
)




_FILTERCONTEXT = _descriptor.Descriptor(
  name='FilterContext',
  full_name='fkhp.page.layer.models.element.FilterContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filterKey', full_name='fkhp.page.layer.models.element.FilterContext.filterKey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filterValue', full_name='fkhp.page.layer.models.element.FilterContext.filterValue', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['FilterContext'] = _FILTERCONTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilterContext = _reflection.GeneratedProtocolMessageType('FilterContext', (_message.Message,), dict(
  DESCRIPTOR = _FILTERCONTEXT,
  __module__ = 'page.models.element.FilterContext_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.page.layer.models.element.FilterContext)
  ))
_sym_db.RegisterMessage(FilterContext)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
