# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/models/enums/AppType.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/models/enums/AppType.proto',
  package='fkhp.page.layer.models.enums',
  syntax='proto3',
  serialized_options=_b('\n\034fkhp.page.layer.models.enumsP\001'),
  serialized_pb=_b('\n\x1fpage/models/enums/AppType.proto\x12\x1c\x66khp.page.layer.models.enums*@\n\x07\x41ppType\x12\x14\n\x10\x44\x45\x46\x41ULT_APP_TYPE\x10\x00\x12\t\n\x05MSITE\x10\x01\x12\x0b\n\x07\x41NDROID\x10\x02\x12\x07\n\x03IOS\x10\x03\x42 \n\x1c\x66khp.page.layer.models.enumsP\x01\x62\x06proto3')
)

_APPTYPE = _descriptor.EnumDescriptor(
  name='AppType',
  full_name='fkhp.page.layer.models.enums.AppType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT_APP_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSITE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANDROID', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IOS', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=65,
  serialized_end=129,
)
_sym_db.RegisterEnumDescriptor(_APPTYPE)

AppType = enum_type_wrapper.EnumTypeWrapper(_APPTYPE)
DEFAULT_APP_TYPE = 0
MSITE = 1
ANDROID = 2
IOS = 3


DESCRIPTOR.enum_types_by_name['AppType'] = _APPTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
