# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/models/enums/PageStatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/models/enums/PageStatus.proto',
  package='fkhp.page.layer.models.enums',
  syntax='proto3',
  serialized_options=_b('\n\034fkhp.page.layer.models.enumsP\001'),
  serialized_pb=_b('\n\"page/models/enums/PageStatus.proto\x12\x1c\x66khp.page.layer.models.enums*B\n\nPageStatus\x12\x17\n\x13\x44\x45\x46\x41ULT_PAGE_STATUS\x10\x00\x12\x0e\n\nPRODUCTION\x10\x01\x12\x0b\n\x07STAGING\x10\x02\x42 \n\x1c\x66khp.page.layer.models.enumsP\x01\x62\x06proto3')
)

_PAGESTATUS = _descriptor.EnumDescriptor(
  name='PageStatus',
  full_name='fkhp.page.layer.models.enums.PageStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT_PAGE_STATUS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRODUCTION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STAGING', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=68,
  serialized_end=134,
)
_sym_db.RegisterEnumDescriptor(_PAGESTATUS)

PageStatus = enum_type_wrapper.EnumTypeWrapper(_PAGESTATUS)
DEFAULT_PAGE_STATUS = 0
PRODUCTION = 1
STAGING = 2


DESCRIPTOR.enum_types_by_name['PageStatus'] = _PAGESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
