# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/models/enums/SectionType.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/models/enums/SectionType.proto',
  package='fkhp.page.layer.models.enums',
  syntax='proto3',
  serialized_options=_b('\n\034fkhp.page.layer.models.enumsP\001'),
  serialized_pb=_b('\n#page/models/enums/SectionType.proto\x12\x1c\x66khp.page.layer.models.enums*:\n\x0bSectionType\x12\x18\n\x14\x44\x45\x46\x41ULT_SECTION_TYPE\x10\x00\x12\x11\n\rPOPUP_SECTION\x10\x01\x42 \n\x1c\x66khp.page.layer.models.enumsP\x01\x62\x06proto3')
)

_SECTIONTYPE = _descriptor.EnumDescriptor(
  name='SectionType',
  full_name='fkhp.page.layer.models.enums.SectionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT_SECTION_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POPUP_SECTION', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=69,
  serialized_end=127,
)
_sym_db.RegisterEnumDescriptor(_SECTIONTYPE)

SectionType = enum_type_wrapper.EnumTypeWrapper(_SECTIONTYPE)
DEFAULT_SECTION_TYPE = 0
POPUP_SECTION = 1


DESCRIPTOR.enum_types_by_name['SectionType'] = _SECTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
