# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/models/enums/UIComponentSubCategoryType.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/models/enums/UIComponentSubCategoryType.proto',
  package='fkhp.page.layer.models.enums',
  syntax='proto3',
  serialized_options=_b('\n\034fkhp.page.layer.models.enumsP\001'),
  serialized_pb=_b('\n2page/models/enums/UIComponentSubCategoryType.proto\x12\x1c\x66khp.page.layer.models.enums*|\n\x1aUIComponentSubCategoryType\x12\"\n\x1e\x44\x45\x46\x41ULT_COMPONENT_SUB_CATEGORY\x10\x00\x12\r\n\tGRID_TYPE\x10\x01\x12\x0f\n\x0bSCROLL_TYPE\x10\x02\x12\x1a\n\x16HORIZONTAL_SCROLL_TYPE\x10\x03\x42 \n\x1c\x66khp.page.layer.models.enumsP\x01\x62\x06proto3')
)

_UICOMPONENTSUBCATEGORYTYPE = _descriptor.EnumDescriptor(
  name='UIComponentSubCategoryType',
  full_name='fkhp.page.layer.models.enums.UIComponentSubCategoryType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT_COMPONENT_SUB_CATEGORY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRID_TYPE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCROLL_TYPE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HORIZONTAL_SCROLL_TYPE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=84,
  serialized_end=208,
)
_sym_db.RegisterEnumDescriptor(_UICOMPONENTSUBCATEGORYTYPE)

UIComponentSubCategoryType = enum_type_wrapper.EnumTypeWrapper(_UICOMPONENTSUBCATEGORYTYPE)
DEFAULT_COMPONENT_SUB_CATEGORY = 0
GRID_TYPE = 1
SCROLL_TYPE = 2
HORIZONTAL_SCROLL_TYPE = 3


DESCRIPTOR.enum_types_by_name['UIComponentSubCategoryType'] = _UICOMPONENTSUBCATEGORYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
