# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/models/enums/UIElementActionType.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/models/enums/UIElementActionType.proto',
  package='fkhp.page.layer.models.enums',
  syntax='proto3',
  serialized_options=_b('\n\034fkhp.page.layer.models.enumsP\001'),
  serialized_pb=_b('\n+page/models/enums/UIElementActionType.proto\x12\x1c\x66khp.page.layer.models.enums*\x8c\x01\n\x13UIElementActionType\x12\x17\n\x13\x44\x45\x46\x41ULT_ACTION_TYPE\x10\x00\x12\n\n\x06SCROLL\x10\x01\x12\x0c\n\x08\x43OLLAPSE\x10\x02\x12\x08\n\x04TYPE\x10\x03\x12\t\n\x05\x43LICK\x10\x04\x12\r\n\tAUTO_FILL\x10\x05\x12\x0f\n\x0bTEXT_FILLER\x10\x06\x12\r\n\tON_CHANGE\x10\x07\x42 \n\x1c\x66khp.page.layer.models.enumsP\x01\x62\x06proto3')
)

_UIELEMENTACTIONTYPE = _descriptor.EnumDescriptor(
  name='UIElementActionType',
  full_name='fkhp.page.layer.models.enums.UIElementActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT_ACTION_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCROLL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLLAPSE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLICK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTO_FILL', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT_FILLER', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_CHANGE', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=78,
  serialized_end=218,
)
_sym_db.RegisterEnumDescriptor(_UIELEMENTACTIONTYPE)

UIElementActionType = enum_type_wrapper.EnumTypeWrapper(_UIELEMENTACTIONTYPE)
DEFAULT_ACTION_TYPE = 0
SCROLL = 1
COLLAPSE = 2
TYPE = 3
CLICK = 4
AUTO_FILL = 5
TEXT_FILLER = 6
ON_CHANGE = 7


DESCRIPTOR.enum_types_by_name['UIElementActionType'] = _UIELEMENTACTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
