# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/request/MoveToProdRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/request/MoveToProdRequest.proto',
  package='fkhp.page.layer.request',
  syntax='proto3',
  serialized_options=_b('\n\027fkhp.page.layer.requestP\001'),
  serialized_pb=_b('\n$page/request/MoveToProdRequest.proto\x12\x17\x66khp.page.layer.request\"\x1f\n\x11MoveToProdRequest\x12\n\n\x02id\x18\x01 \x01(\tB\x1b\n\x17\x66khp.page.layer.requestP\x01\x62\x06proto3')
)




_MOVETOPRODREQUEST = _descriptor.Descriptor(
  name='MoveToProdRequest',
  full_name='fkhp.page.layer.request.MoveToProdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='fkhp.page.layer.request.MoveToProdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['MoveToProdRequest'] = _MOVETOPRODREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MoveToProdRequest = _reflection.GeneratedProtocolMessageType('MoveToProdRequest', (_message.Message,), dict(
  DESCRIPTOR = _MOVETOPRODREQUEST,
  __module__ = 'page.request.MoveToProdRequest_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.page.layer.request.MoveToProdRequest)
  ))
_sym_db.RegisterMessage(MoveToProdRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
