# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/models/section/pmp/PageSectionUserInputModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from page.models.enums import SectionType_pb2 as page_dot_models_dot_enums_dot_SectionType__pb2
from page.models.design.pmp import DesignParameter_pb2 as page_dot_models_dot_design_dot_pmp_dot_DesignParameter__pb2
from page.models.component.pmp import UIComponentUserInputModel_pb2 as page_dot_models_dot_component_dot_pmp_dot_UIComponentUserInputModel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/models/section/pmp/PageSectionUserInputModel.proto',
  package='fkhp.page.layer.models.section.pmp',
  syntax='proto3',
  serialized_options=_b('\n\"fkhp.page.layer.models.section.pmpP\001'),
  serialized_pb=_b('\n7page/models/section/pmp/PageSectionUserInputModel.proto\x12\"fkhp.page.layer.models.section.pmp\x1a#page/models/enums/SectionType.proto\x1a,page/models/design/pmp/DesignParameter.proto\x1a\x39page/models/component/pmp/UIComponentUserInputModel.proto\"\xb0\x02\n\x19PageSectionUserInputModel\x12\x11\n\tsectionId\x18\x01 \x01(\t\x12\r\n\x05order\x18\x02 \x01(\x05\x12>\n\x0bsectionType\x18\x03 \x01(\x0e\x32).fkhp.page.layer.models.enums.SectionType\x12L\n\x10\x64\x65signParameters\x18\x04 \x03(\x0b\x32\x32.fkhp.page.layer.models.design.pmp.DesignParameter\x12\x63\n\x1auiComponentUserInputModels\x18\x05 \x03(\x0b\x32?.fkhp.page.layer.models.component.pmp.UIComponentUserInputModelB&\n\"fkhp.page.layer.models.section.pmpP\x01\x62\x06proto3')
  ,
  dependencies=[page_dot_models_dot_enums_dot_SectionType__pb2.DESCRIPTOR,page_dot_models_dot_design_dot_pmp_dot_DesignParameter__pb2.DESCRIPTOR,page_dot_models_dot_component_dot_pmp_dot_UIComponentUserInputModel__pb2.DESCRIPTOR,])




_PAGESECTIONUSERINPUTMODEL = _descriptor.Descriptor(
  name='PageSectionUserInputModel',
  full_name='fkhp.page.layer.models.section.pmp.PageSectionUserInputModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sectionId', full_name='fkhp.page.layer.models.section.pmp.PageSectionUserInputModel.sectionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order', full_name='fkhp.page.layer.models.section.pmp.PageSectionUserInputModel.order', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sectionType', full_name='fkhp.page.layer.models.section.pmp.PageSectionUserInputModel.sectionType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='designParameters', full_name='fkhp.page.layer.models.section.pmp.PageSectionUserInputModel.designParameters', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uiComponentUserInputModels', full_name='fkhp.page.layer.models.section.pmp.PageSectionUserInputModel.uiComponentUserInputModels', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=542,
)

_PAGESECTIONUSERINPUTMODEL.fields_by_name['sectionType'].enum_type = page_dot_models_dot_enums_dot_SectionType__pb2._SECTIONTYPE
_PAGESECTIONUSERINPUTMODEL.fields_by_name['designParameters'].message_type = page_dot_models_dot_design_dot_pmp_dot_DesignParameter__pb2._DESIGNPARAMETER
_PAGESECTIONUSERINPUTMODEL.fields_by_name['uiComponentUserInputModels'].message_type = page_dot_models_dot_component_dot_pmp_dot_UIComponentUserInputModel__pb2._UICOMPONENTUSERINPUTMODEL
DESCRIPTOR.message_types_by_name['PageSectionUserInputModel'] = _PAGESECTIONUSERINPUTMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PageSectionUserInputModel = _reflection.GeneratedProtocolMessageType('PageSectionUserInputModel', (_message.Message,), dict(
  DESCRIPTOR = _PAGESECTIONUSERINPUTMODEL,
  __module__ = 'page.models.section.pmp.PageSectionUserInputModel_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.page.layer.models.section.pmp.PageSectionUserInputModel)
  ))
_sym_db.RegisterMessage(PageSectionUserInputModel)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
