# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/request/AddAndUpdateAddressViewRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import requestMetaInfo_pb2 as executor_dot_models_dot_requestMetaInfo__pb2
from executor.models import addressType_pb2 as executor_dot_models_dot_addressType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/request/AddAndUpdateAddressViewRequest.proto',
  package='fkhp.data.layer.executor.request',
  syntax='proto3',
  serialized_options=_b('\n fkhp.data.layer.executor.requestP\001'),
  serialized_pb=_b('\n5executor/request/AddAndUpdateAddressViewRequest.proto\x12 fkhp.data.layer.executor.request\x1a%executor/models/requestMetaInfo.proto\x1a!executor/models/addressType.proto\"\xf7\x02\n\x1e\x41\x64\x64\x41ndUpdateAddressViewRequest\x12@\n\nactionType\x18\x01 \x01(\x0e\x32,.fkhp.data.layer.executor.request.ActionType\x12I\n\x0frequestMetaInfo\x18\x02 \x01(\x0b\x32\x30.fkhp.data.layer.executor.models.RequestMetaInfo\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0cmobileNumber\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\x12\x10\n\x08landmark\x18\x06 \x01(\t\x12\x0f\n\x07pinCode\x18\x07 \x01(\t\x12\x0c\n\x04\x63ity\x18\x08 \x01(\t\x12\x0c\n\x04\x61rea\x18\t \x01(\t\x12\x41\n\x0b\x61\x64\x64ressType\x18\n \x01(\x0e\x32,.fkhp.data.layer.executor.models.AddressType\x12\x11\n\taddressId\x18\x0b \x01(\t*\x1f\n\nActionType\x12\x08\n\x04\x45\x44IT\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x42$\n fkhp.data.layer.executor.requestP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_requestMetaInfo__pb2.DESCRIPTOR,executor_dot_models_dot_addressType__pb2.DESCRIPTOR,])

_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='fkhp.data.layer.executor.request.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EDIT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=543,
  serialized_end=574,
)
_sym_db.RegisterEnumDescriptor(_ACTIONTYPE)

ActionType = enum_type_wrapper.EnumTypeWrapper(_ACTIONTYPE)
EDIT = 0
ADD = 1



_ADDANDUPDATEADDRESSVIEWREQUEST = _descriptor.Descriptor(
  name='AddAndUpdateAddressViewRequest',
  full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actionType', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.actionType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestMetaInfo', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.requestMetaInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobileNumber', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.mobileNumber', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.address', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landmark', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.landmark', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pinCode', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.pinCode', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.city', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='area', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.area', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addressType', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.addressType', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addressId', full_name='fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest.addressId', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=541,
)

_ADDANDUPDATEADDRESSVIEWREQUEST.fields_by_name['actionType'].enum_type = _ACTIONTYPE
_ADDANDUPDATEADDRESSVIEWREQUEST.fields_by_name['requestMetaInfo'].message_type = executor_dot_models_dot_requestMetaInfo__pb2._REQUESTMETAINFO
_ADDANDUPDATEADDRESSVIEWREQUEST.fields_by_name['addressType'].enum_type = executor_dot_models_dot_addressType__pb2._ADDRESSTYPE
DESCRIPTOR.message_types_by_name['AddAndUpdateAddressViewRequest'] = _ADDANDUPDATEADDRESSVIEWREQUEST
DESCRIPTOR.enum_types_by_name['ActionType'] = _ACTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddAndUpdateAddressViewRequest = _reflection.GeneratedProtocolMessageType('AddAndUpdateAddressViewRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDANDUPDATEADDRESSVIEWREQUEST,
  __module__ = 'executor.request.AddAndUpdateAddressViewRequest_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.request.AddAndUpdateAddressViewRequest)
  ))
_sym_db.RegisterMessage(AddAndUpdateAddressViewRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
