# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/request/AddressDetailFromLocationPointViewRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import deviceInfo_pb2 as executor_dot_models_dot_deviceInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/request/AddressDetailFromLocationPointViewRequest.proto',
  package='fkhp.data.layer.executor.request',
  syntax='proto3',
  serialized_options=_b('\n fkhp.data.layer.executor.requestP\001'),
  serialized_pb=_b('\n@executor/request/AddressDetailFromLocationPointViewRequest.proto\x12 fkhp.data.layer.executor.request\x1a executor/models/deviceInfo.proto\"P\n)AddressDetailFromLocationPointViewRequest\x12\x10\n\x08latitude\x18\x01 \x01(\t\x12\x11\n\tlongitude\x18\x02 \x01(\tB$\n fkhp.data.layer.executor.requestP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_deviceInfo__pb2.DESCRIPTOR,])




_ADDRESSDETAILFROMLOCATIONPOINTVIEWREQUEST = _descriptor.Descriptor(
  name='AddressDetailFromLocationPointViewRequest',
  full_name='fkhp.data.layer.executor.request.AddressDetailFromLocationPointViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='fkhp.data.layer.executor.request.AddressDetailFromLocationPointViewRequest.latitude', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='fkhp.data.layer.executor.request.AddressDetailFromLocationPointViewRequest.longitude', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['AddressDetailFromLocationPointViewRequest'] = _ADDRESSDETAILFROMLOCATIONPOINTVIEWREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressDetailFromLocationPointViewRequest = _reflection.GeneratedProtocolMessageType('AddressDetailFromLocationPointViewRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSDETAILFROMLOCATIONPOINTVIEWREQUEST,
  __module__ = 'executor.request.AddressDetailFromLocationPointViewRequest_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.request.AddressDetailFromLocationPointViewRequest)
  ))
_sym_db.RegisterMessage(AddressDetailFromLocationPointViewRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
