# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/request/AddressSuggestionViewRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/request/AddressSuggestionViewRequest.proto',
  package='fkhp.data.layer.executor.request',
  syntax='proto3',
  serialized_options=_b('\n fkhp.data.layer.executor.requestP\001'),
  serialized_pb=_b('\n3executor/request/AddressSuggestionViewRequest.proto\x12 fkhp.data.layer.executor.request\"\x92\x01\n\x1c\x41\x64\x64ressSuggestionViewRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x45\n\x04type\x18\x02 \x01(\x0e\x32\x37.fkhp.data.layer.executor.request.AddressSuggestionType\x12\x0e\n\x06region\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x05*\xc5\x01\n\x15\x41\x64\x64ressSuggestionType\x12\x1b\n\x17\x41\x44\x44RESS_SUGGESTION_TYPE\x10\x00\x12\n\n\x06TYPEAP\x10\x01\x12\x0b\n\x07TYPEPOI\x10\x02\x12\x0b\n\x07TYPELOC\x10\x03\x12\x0c\n\x08TYPESUBL\x10\x04\x12\x0c\n\x08TYPESSLC\x10\x05\x12\x0b\n\x07TYPECTY\x10\x06\x12\x0c\n\x08TYPESCTY\x10\x07\x12\x0b\n\x07TYPEDST\x10\x08\x12\x0b\n\x07TYPESDB\x10\t\x12\x0b\n\x07TYPEVLG\x10\n\x12\x0b\n\x07TYPEPIN\x10\x0b\x42$\n fkhp.data.layer.executor.requestP\x01\x62\x06proto3')
)

_ADDRESSSUGGESTIONTYPE = _descriptor.EnumDescriptor(
  name='AddressSuggestionType',
  full_name='fkhp.data.layer.executor.request.AddressSuggestionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADDRESS_SUGGESTION_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPEAP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPEPOI', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPELOC', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPESUBL', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPESSLC', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPECTY', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPESCTY', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPEDST', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPESDB', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPEVLG', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPEPIN', index=11, number=11,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=239,
  serialized_end=436,
)
_sym_db.RegisterEnumDescriptor(_ADDRESSSUGGESTIONTYPE)

AddressSuggestionType = enum_type_wrapper.EnumTypeWrapper(_ADDRESSSUGGESTIONTYPE)
ADDRESS_SUGGESTION_TYPE = 0
TYPEAP = 1
TYPEPOI = 2
TYPELOC = 3
TYPESUBL = 4
TYPESSLC = 5
TYPECTY = 6
TYPESCTY = 7
TYPEDST = 8
TYPESDB = 9
TYPEVLG = 10
TYPEPIN = 11



_ADDRESSSUGGESTIONVIEWREQUEST = _descriptor.Descriptor(
  name='AddressSuggestionViewRequest',
  full_name='fkhp.data.layer.executor.request.AddressSuggestionViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='fkhp.data.layer.executor.request.AddressSuggestionViewRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='fkhp.data.layer.executor.request.AddressSuggestionViewRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region', full_name='fkhp.data.layer.executor.request.AddressSuggestionViewRequest.region', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='fkhp.data.layer.executor.request.AddressSuggestionViewRequest.count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=236,
)

_ADDRESSSUGGESTIONVIEWREQUEST.fields_by_name['type'].enum_type = _ADDRESSSUGGESTIONTYPE
DESCRIPTOR.message_types_by_name['AddressSuggestionViewRequest'] = _ADDRESSSUGGESTIONVIEWREQUEST
DESCRIPTOR.enum_types_by_name['AddressSuggestionType'] = _ADDRESSSUGGESTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressSuggestionViewRequest = _reflection.GeneratedProtocolMessageType('AddressSuggestionViewRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSSUGGESTIONVIEWREQUEST,
  __module__ = 'executor.request.AddressSuggestionViewRequest_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.request.AddressSuggestionViewRequest)
  ))
_sym_db.RegisterMessage(AddressSuggestionViewRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
