# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/request/AddToCartViewRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import userInfo_pb2 as executor_dot_models_dot_userInfo__pb2
from executor.models import requestMetaInfo_pb2 as executor_dot_models_dot_requestMetaInfo__pb2
from executor.models import addToCartProductInfo_pb2 as executor_dot_models_dot_addToCartProductInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/request/AddToCartViewRequest.proto',
  package='fkhp.data.layer.executor.request',
  syntax='proto3',
  serialized_options=_b('\n fkhp.data.layer.executor.requestP\001'),
  serialized_pb=_b('\n+executor/request/AddToCartViewRequest.proto\x12 fkhp.data.layer.executor.request\x1a\x1e\x65xecutor/models/userInfo.proto\x1a%executor/models/requestMetaInfo.proto\x1a*executor/models/addToCartProductInfo.proto\"\xbd\x02\n\x14\x41\x64\x64ToCartViewRequest\x12;\n\x08userInfo\x18\x01 \x01(\x0b\x32).fkhp.data.layer.executor.models.UserInfo\x12I\n\x0frequestMetaInfo\x18\x02 \x01(\x0b\x32\x30.fkhp.data.layer.executor.models.RequestMetaInfo\x12G\n\x08products\x18\x03 \x03(\x0b\x32\x35.fkhp.data.layer.executor.models.AddToCartProductInfo\x12\x46\n\raddToCartType\x18\x04 \x01(\x0e\x32/.fkhp.data.layer.executor.request.AddToCartType\x12\x0c\n\x04page\x18\x05 \x01(\t*\x7f\n\rAddToCartType\x12\x0c\n\x08\x43HECKOUT\x10\x00\x12\x08\n\x04\x43\x41RT\x10\x01\x12\x14\n\x10\x44\x45LETE_FROM_CART\x10\x02\x12\x16\n\x12\x44\x45LETE_FROM_BASKET\x10\x03\x12\n\n\x06\x42\x41SKET\x10\x04\x12\x0c\n\x08GET_CART\x10\x05\x12\x0e\n\nGET_BASKET\x10\x06\x42$\n fkhp.data.layer.executor.requestP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_userInfo__pb2.DESCRIPTOR,executor_dot_models_dot_requestMetaInfo__pb2.DESCRIPTOR,executor_dot_models_dot_addToCartProductInfo__pb2.DESCRIPTOR,])

_ADDTOCARTTYPE = _descriptor.EnumDescriptor(
  name='AddToCartType',
  full_name='fkhp.data.layer.executor.request.AddToCartType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHECKOUT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CART', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_FROM_CART', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_FROM_BASKET', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASKET', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_CART', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_BASKET', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=516,
  serialized_end=643,
)
_sym_db.RegisterEnumDescriptor(_ADDTOCARTTYPE)

AddToCartType = enum_type_wrapper.EnumTypeWrapper(_ADDTOCARTTYPE)
CHECKOUT = 0
CART = 1
DELETE_FROM_CART = 2
DELETE_FROM_BASKET = 3
BASKET = 4
GET_CART = 5
GET_BASKET = 6



_ADDTOCARTVIEWREQUEST = _descriptor.Descriptor(
  name='AddToCartViewRequest',
  full_name='fkhp.data.layer.executor.request.AddToCartViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='fkhp.data.layer.executor.request.AddToCartViewRequest.userInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestMetaInfo', full_name='fkhp.data.layer.executor.request.AddToCartViewRequest.requestMetaInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='products', full_name='fkhp.data.layer.executor.request.AddToCartViewRequest.products', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addToCartType', full_name='fkhp.data.layer.executor.request.AddToCartViewRequest.addToCartType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page', full_name='fkhp.data.layer.executor.request.AddToCartViewRequest.page', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=514,
)

_ADDTOCARTVIEWREQUEST.fields_by_name['userInfo'].message_type = executor_dot_models_dot_userInfo__pb2._USERINFO
_ADDTOCARTVIEWREQUEST.fields_by_name['requestMetaInfo'].message_type = executor_dot_models_dot_requestMetaInfo__pb2._REQUESTMETAINFO
_ADDTOCARTVIEWREQUEST.fields_by_name['products'].message_type = executor_dot_models_dot_addToCartProductInfo__pb2._ADDTOCARTPRODUCTINFO
_ADDTOCARTVIEWREQUEST.fields_by_name['addToCartType'].enum_type = _ADDTOCARTTYPE
DESCRIPTOR.message_types_by_name['AddToCartViewRequest'] = _ADDTOCARTVIEWREQUEST
DESCRIPTOR.enum_types_by_name['AddToCartType'] = _ADDTOCARTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddToCartViewRequest = _reflection.GeneratedProtocolMessageType('AddToCartViewRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDTOCARTVIEWREQUEST,
  __module__ = 'executor.request.AddToCartViewRequest_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.request.AddToCartViewRequest)
  ))
_sym_db.RegisterMessage(AddToCartViewRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
