# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor/request/SetCurrentLocationViewRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from executor.models import requestMetaInfo_pb2 as executor_dot_models_dot_requestMetaInfo__pb2
from executor.models import query_pb2 as executor_dot_models_dot_query__pb2
from executor.models import filter_pb2 as executor_dot_models_dot_filter__pb2
from executor.models import sortInfo_pb2 as executor_dot_models_dot_sortInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor/request/SetCurrentLocationViewRequest.proto',
  package='fkhp.data.layer.executor.request',
  syntax='proto3',
  serialized_options=_b('\n fkhp.data.layer.executor.requestP\001'),
  serialized_pb=_b('\n4executor/request/SetCurrentLocationViewRequest.proto\x12 fkhp.data.layer.executor.request\x1a%executor/models/requestMetaInfo.proto\x1a\x1b\x65xecutor/models/query.proto\x1a\x1c\x65xecutor/models/filter.proto\x1a\x1e\x65xecutor/models/sortInfo.proto\"\x8f\x01\n\x1dSetCurrentLocationViewRequest\x12I\n\x0frequestMetaInfo\x18\x01 \x01(\x0b\x32\x30.fkhp.data.layer.executor.models.RequestMetaInfo\x12\x11\n\tlongitude\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\tB$\n fkhp.data.layer.executor.requestP\x01\x62\x06proto3')
  ,
  dependencies=[executor_dot_models_dot_requestMetaInfo__pb2.DESCRIPTOR,executor_dot_models_dot_query__pb2.DESCRIPTOR,executor_dot_models_dot_filter__pb2.DESCRIPTOR,executor_dot_models_dot_sortInfo__pb2.DESCRIPTOR,])




_SETCURRENTLOCATIONVIEWREQUEST = _descriptor.Descriptor(
  name='SetCurrentLocationViewRequest',
  full_name='fkhp.data.layer.executor.request.SetCurrentLocationViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestMetaInfo', full_name='fkhp.data.layer.executor.request.SetCurrentLocationViewRequest.requestMetaInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='fkhp.data.layer.executor.request.SetCurrentLocationViewRequest.longitude', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='fkhp.data.layer.executor.request.SetCurrentLocationViewRequest.latitude', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=364,
)

_SETCURRENTLOCATIONVIEWREQUEST.fields_by_name['requestMetaInfo'].message_type = executor_dot_models_dot_requestMetaInfo__pb2._REQUESTMETAINFO
DESCRIPTOR.message_types_by_name['SetCurrentLocationViewRequest'] = _SETCURRENTLOCATIONVIEWREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetCurrentLocationViewRequest = _reflection.GeneratedProtocolMessageType('SetCurrentLocationViewRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETCURRENTLOCATIONVIEWREQUEST,
  __module__ = 'executor.request.SetCurrentLocationViewRequest_pb2'
  # @@protoc_insertion_point(class_scope:fkhp.data.layer.executor.request.SetCurrentLocationViewRequest)
  ))
_sym_db.RegisterMessage(SetCurrentLocationViewRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
